# Idea
Do some training

In [52]:
SEED = 133
TIME_WINDOW = "30s"
DATA_FILE = '../../data/all_df_30s_Xi_sensor_1.csv'

COLUMNS_SELECTION_FILE_FROM_RP4 = "../other_time_windows/weight_selected_30s.csv"

In [53]:
from pathlib import Path

import numpy as np
import pandas as pd
import pickle

assert Path(DATA_FILE).exists()

In [54]:
import sys
repo_base_path = Path("./../../../").resolve()
assert str(repo_base_path).endswith("csg_is"), f"{repo_base_path} is not a valid path to the CSG_IS repository" 

sys.path.append(str(repo_base_path))
sys.path.append("..")

# from py_dataset import get_all_files_df
# from py_dataset import read_in_files
from py_dataset import feature_plotting
# from py_dataset import feature_selection
# from py_dataset import net_feature_engineering
# from py_dataset import entropy_feature_engineering
# from py_dataset.classes import DataSource
from py_dataset import sys_func

from py_dataset.classes import DataSource



In [55]:
LOG_PATH = (repo_base_path / "training" / "official_logs")
LOG_NAME = f"single-layer_300_{TIME_WINDOW}_Xi_sensor_1_rp3"
LOG_NAME_EXPERIMENT_2 = f"single-layer_30_from_rp4_weights_{TIME_WINDOW}_Xi_sensor_1_rp3"
LOG_NAME_EXPERIMENT_3 = f"multi-layer_30_from_rp4_weights_{TIME_WINDOW}_Xi_sensor_1_rp3"

assert LOG_PATH.exists()
assert not (LOG_PATH / LOG_NAME).exists(), "are you sure to run this again?"
assert not (LOG_PATH / LOG_NAME_EXPERIMENT_2).exists(), "are you sure to run this again?"
assert not (LOG_PATH / LOG_NAME_EXPERIMENT_3).exists(), "are you sure to run this again?"

AssertionError: are you sure to run this again?

In [ ]:
df = pd.read_csv(DATA_FILE)
df.set_index("timestamp", inplace=True)

/tmp/ipykernel_239875/1931635172.py:1: DtypeWarning: Columns (189) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_FILE)


In [ ]:
assert df["label"].unique().shape == (10,)

In [ ]:
selected_columns = pd.read_csv(COLUMNS_SELECTION_FILE_FROM_RP4)["0"].values

### Preprocessings
- remove Null values
- drop timestamp
- labelEncode
- normalize

In [ ]:
print(df.shape)
old_df = df.copy()
df.dropna(axis=0, how='any', inplace=True)

print(df.shape)

(38686, 288)
(21550, 288)


In [ ]:
df.reset_index(inplace=True, drop=True)

In [ ]:
label_encoder = sys_func.create_label_encoder_for_labels()
df['label'] = label_encoder.transform(df['label'])

In [ ]:
df = feature_plotting.test_transform_all_to_numeric_columns(df)

In [ ]:
cols_to_exclude_from_scaling = ["label"]
vectors = feature_plotting.minmax_scale_features(df,remove_outliers_iqr_all_columns=False,
                                                        cols_to_exclude_from_scaling=cols_to_exclude_from_scaling)
# print(vectors.shape)
# print(" with dropped null: ", vectors.dropna(axis=0, how='any', inplace=False).shape)

In [ ]:
df["label"].unique(), vectors["label"].unique()

(array([0, 8, 4, 1, 5, 2, 7, 6, 3]), array([0, 8, 4, 1, 5, 2, 7, 6, 3]))

### Setup

In [ ]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomeDataset(Dataset):
    def __init__(self, some_df:pd.DataFrame):
        
        self.x = torch.tensor(some_df.drop(columns=["label"], inplace=False).values, dtype=torch.float32)
        self.labels = torch.tensor(some_df["label"].values, dtype=torch.uint8)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        # if torch.is_tensor(idx):
        #     idx = idx.tolist()
        # print(self.x[idx], self.labels[idx])
        return self.x[idx], self.labels[idx]

In [ ]:
from mlp_single_layer import MalwaresModelLinearLayer
from torch.utils.data import DataLoader
import lightning
from sklearn.model_selection import train_test_split
from lightning import loggers as pl_loggers
from lightning.pytorch.callbacks.early_stopping import EarlyStopping
from lightning.pytorch.callbacks.model_checkpoint import ModelCheckpoint

tensorboard = pl_loggers.TensorBoardLogger(save_dir=LOG_PATH, name=LOG_NAME)

# split into train and val
train, val = train_test_split(vectors, test_size=0.2, random_state=SEED)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True, logger=tensorboard) #logger=None, 


model = MalwaresModelLinearLayer(input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_), seed=SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [ ]:
trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 2.6 K 
------------------------------------------------------------
2.6 K     Trainable params
0         Non-trainable params
2.6 K     Total params
0.010     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[  0,   0,   0,   0,   1, 105,   0,   0,   0],
        [  0,   0,   0,   0,   5, 102,   0,   0,   0],
        [  0,   0,   0,   0,   0,  93,   0,   0,   0],
        [ 11,   0,   0,   0,   0, 106,   1,   0,   0],
        [  0,   0,   0,   0,   0,  98,   0,   0,   0],
        [  0,   0,   0,   0,   0, 115,   0,   0,   0],
        [ 15,   0,   0,   0,  12, 100,   0,   0,   0],
        [  9,   0,   0,   0,   2,  99,   0,   0,   0],
        [  0,  12,   0,   0,   0, 114,   0,   0,   0]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (35) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[1709,    0,  214,    0,  419,  153,    0,    0,   11],
        [   0, 2346,    0,    0,    8,  158,    0,    0,    0],
        [ 246,    3, 1907,    0,  112,  230,    0,    0,    0],
        [  15,    8,    0, 2274,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 2051,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 2341,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 2096,  206,    0],
        [  11,    0,    0,    0,    4,  149,  239, 2107,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 2239]])
Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[1709,    0,  214,    0,  419,  153,    0,    0,   11],
        [   0, 2346,    0,    0,    8,  158,    0,    0,    0],
        [ 246,    3, 1907,    0,  112,  230,    0,    0,    0],
        [  15,    8,    0, 2274,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 2051,  159,    0,    0,   

Metric Validation/Accuracy improved. New best score: 0.993


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[4105,    0,  218,    0,  419,  153,    0,    0,   11],
        [   0, 4751,    0,    0,    8,  158,    0,    0,    0],
        [ 417,    3, 4141,    0,  112,  230,    0,    0,    0],
        [  15,    8,    5, 4664,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 4451,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 4741,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 4443,  214,    0],
        [  11,    0,    0,    0,    4,  149,  244, 4502,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 4629]])


Metric Validation/Accuracy improved by 0.000 >= min_delta = 0.0. New best score: 0.994


Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[4105,    0,  218,    0,  419,  153,    0,    0,   11],
        [   0, 4751,    0,    0,    8,  158,    0,    0,    0],
        [ 417,    3, 4141,    0,  112,  230,    0,    0,    0],
        [  15,    8,    5, 4664,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 4451,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 4741,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 4443,  214,    0],
        [  11,    0,    0,    0,    4,  149,  244, 4502,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 4629]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[6503,    0,  220,    0,  419,  153,    0,    0,   11],
        [   0, 7156,    0,    0,    8,  158,    0,    0,    0],
        [ 540,    3, 6423,    0,  112,  230,    0,    0,    0],
        [  15,    8,   10, 7054,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 6851,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 7141,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 6798,  214,    0],
        [  11,    0,    0,    0,    4,  149,  249, 6897,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 7019]])
Epoch end: Train, epoch number: 2
TrainEpoch/CM
 tensor([[6503,    0,  220,    0,  419,  153,    0,    0,   11],
        [   0, 7156,    0,    0,    8,  158,    0,    0,    0],
        [ 540,    3, 6423,    0,  112,  230,    0,    0,    0],
        [  15,    8,   10, 7054,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 6851,  159,    0,    0,   

Metric Validation/Accuracy improved by 0.001 >= min_delta = 0.0. New best score: 0.995


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[8902,    0,  221,    0,  419,  153,    0,    0,   11],
        [   0, 9561,    0,    0,    8,  158,    0,    0,    0],
        [ 630,    3, 8738,    0,  112,  230,    0,    0,    0],
        [  15,    8,   15, 9444,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 9251,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 9541,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 9153,  214,    0],
        [  11,    0,    0,    0,    4,  149,  254, 9292,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 9409]])


Metric Validation/Accuracy improved by 0.001 >= min_delta = 0.0. New best score: 0.996


Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[8902,    0,  221,    0,  419,  153,    0,    0,   11],
        [   0, 9561,    0,    0,    8,  158,    0,    0,    0],
        [ 630,    3, 8738,    0,  112,  230,    0,    0,    0],
        [  15,    8,   15, 9444,    0,  159,   57,    0,    0],
        [ 159,    0,  129,    0, 9251,  159,    0,    0,    0],
        [   3,   45,  126,    0,    0, 9541,    0,    0,    0],
        [  23,    0,    0,    0,   14,  143, 9153,  214,    0],
        [  11,    0,    0,    0,    4,  149,  254, 9292,    0],
        [   0,   55,   55,    0,    0,  167,    0,    0, 9409]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[11302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 11966,     0,     0,     8,   158,     0,     0,     0],
        [  693,     3, 11080,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 11836,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 11651,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 11941,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 11508,   214,     0],
        [   11,     0,     0,     0,     4,   149,   259, 11687,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 11799]])
Epoch end: Train, epoch number: 4
TrainEpoch/CM
 tensor([[11302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 11966,     0,     0,     8,   158,     0,     0,     0],
        [  693,     3, 11080,     0,   112,   230,     0,     0,     0],
        [   15,

Metric Validation/Accuracy improved by 0.002 >= min_delta = 0.0. New best score: 0.998


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[13702,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 14371,     0,     0,     8,   158,     0,     0,     0],
        [  738,     3, 13440,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 14231,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 14051,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 14341,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 13863,   214,     0],
        [   11,     0,     0,     0,     4,   149,   264, 14082,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 14189]])
Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[13702,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 14371,     0,     0,     8,   158,     0,     0,     0],
        [  738,     3, 13440,     0,   112,   230,     0,     0,     0],
        [   15,

Metric Validation/Accuracy improved by 0.000 >= min_delta = 0.0. New best score: 0.998


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[16102,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 16776,     0,     0,     8,   158,     0,     0,     0],
        [  765,     3, 15818,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 16626,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 16451,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 16741,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 16218,   214,     0],
        [   11,     0,     0,     0,     4,   149,   269, 16477,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 16579]])


Metric Validation/Accuracy improved by 0.001 >= min_delta = 0.0. New best score: 1.000


Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[16102,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 16776,     0,     0,     8,   158,     0,     0,     0],
        [  765,     3, 15818,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 16626,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 16451,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 16741,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 16218,   214,     0],
        [   11,     0,     0,     0,     4,   149,   269, 16477,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 16579]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[18502,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 19181,     0,     0,     8,   158,     0,     0,     0],
        [  783,     3, 18205,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 19021,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 18851,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 19141,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 18573,   214,     0],
        [   11,     0,     0,     0,     4,   149,   274, 18872,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 18969]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[18502,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 19181,     0,     0,     8,   158,     0,     0,     0],
        [  783,     3, 18205,     0,   112,   230,     0,     0,     0],
        [   15,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[20902,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 21586,     0,     0,     8,   158,     0,     0,     0],
        [  798,     3, 20595,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 21416,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 21251,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 21541,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 20928,   214,     0],
        [   11,     0,     0,     0,     4,   149,   279, 21267,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 21359]])
Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[20902,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 21586,     0,     0,     8,   158,     0,     0,     0],
        [  798,     3, 20595,     0,   112,   230,     0,     0,     0],
        [   15,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[23302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 23991,     0,     0,     8,   158,     0,     0,     0],
        [  812,     3, 22986,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 23811,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 23651,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 23941,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 23283,   214,     0],
        [   11,     0,     0,     0,     4,   149,   281, 23665,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 23749]])
Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[23302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 23991,     0,     0,     8,   158,     0,     0,     0],
        [  812,     3, 22986,     0,   112,   230,     0,     0,     0],
        [   15

Metric Validation/Accuracy improved by 0.000 >= min_delta = 0.0. New best score: 1.000


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[25702,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 26396,     0,     0,     8,   158,     0,     0,     0],
        [  826,     3, 25377,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 26206,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 26051,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 26341,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 25638,   214,     0],
        [   11,     0,     0,     0,     4,   149,   282, 26064,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 26139]])
Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[25702,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 26396,     0,     0,     8,   158,     0,     0,     0],
        [  826,     3, 25377,     0,   112,   230,     0,     0,     0],
        [   1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[28102,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 28801,     0,     0,     8,   158,     0,     0,     0],
        [  840,     3, 27768,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 28601,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 28451,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 28741,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 27993,   214,     0],
        [   11,     0,     0,     0,     4,   149,   282, 28464,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 28529]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[28102,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 28801,     0,     0,     8,   158,     0,     0,     0],
        [  840,     3, 27768,     0,   112,   230,     0,     0,     0],
        [   1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[30502,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 31206,     0,     0,     8,   158,     0,     0,     0],
        [  853,     3, 30160,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 30996,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 30851,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 31141,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 30348,   214,     0],
        [   11,     0,     0,     0,     4,   149,   282, 30864,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 30919]])
Epoch end: Train, epoch number: 12
TrainEpoch/CM
 tensor([[30502,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 31206,     0,     0,     8,   158,     0,     0,     0],
        [  853,     3, 30160,     0,   112,   230,     0,     0,     0],
        [   1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[32902,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 33611,     0,     0,     8,   158,     0,     0,     0],
        [  865,     3, 32553,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 33391,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 33251,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 33541,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 32703,   214,     0],
        [   11,     0,     0,     0,     4,   149,   282, 33264,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 33309]])
Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[32902,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 33611,     0,     0,     8,   158,     0,     0,     0],
        [  865,     3, 32553,     0,   112,   230,     0,     0,     0],
        [   1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[35302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 36016,     0,     0,     8,   158,     0,     0,     0],
        [  875,     3, 34948,     0,   112,   230,     0,     0,     0],
        [   15,     8,    18, 35786,     0,   159,    57,     0,     0],
        [  159,     0,   129,     0, 35651,   159,     0,     0,     0],
        [    3,    45,   126,     0,     0, 35941,     0,     0,     0],
        [   23,     0,     0,     0,    14,   143, 35058,   214,     0],
        [   11,     0,     0,     0,     4,   149,   282, 35664,     0],
        [    0,    55,    55,     0,     0,   167,     0,     0, 35699]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[35302,     0,   221,     0,   419,   153,     0,     0,    11],
        [    0, 36016,     0,     0,     8,   158,     0,     0,     0],
        [  875,     3, 34948,     0,   112,   230,     0,     0,     0],
        [   1

Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 1.000. Signaling Trainer to stop.


In [ ]:
model.eval()

MalwaresModelLinearLayer(
  (train_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Train/
  )
  (val_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Validation/
  )
  (test_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Test/
  )
  (cm): MulticlassConfusionMatrix()
  (criterion): CrossEntropyLoss()
  (l1): Linear(in_features=287, out_features=9, bias=True)
)

In [ ]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelLinearLayer.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/official_logs/single-layer_300_30s_Xi_sensor_1_rp3/version_0/checkpoints/epoch=9-step=350.ckpt
tensor(1., device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[480,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0, 474,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0, 479,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0, 462,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 485,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 478,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0, 482,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0, 485,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 485]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy                 1.0
      Test/F1Score                  1.0
        Test/Loss          0.024981120601296425
     Test/Precision                 1.0
   

[{'Test/Loss': 0.024981120601296425,
  'Test/Accuracy': 1.0,
  'Test/Precision': 1.0,
  'Test/Recall': 1.0,
  'Test/F1Score': 1.0,
  'TestEpoch/Accuracy': 1.0,
  'TestEpoch/Precision': 1.0,
  'TestEpoch/Recall': 1.0,
  'TestEpoch/F1Score': 1.0}]

### Train again

In [ ]:
print ("going to remove columns: ", set(selected_columns) - set(vectors.columns))
selected_columns_that_are_in_rp3_dataset = list(set(selected_columns) & set(vectors.columns))

going to remove columns:  {'armv7_cortex_a15/br_mis_pred/'}


In [56]:
vectors[selected_columns_that_are_in_rp3_dataset].shape

(21550, 32)

In [57]:
subset = vectors[selected_columns_that_are_in_rp3_dataset]
subset["label"] = df["label"]

/tmp/ipykernel_239875/468855836.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset["label"] = df["label"]


In [58]:
# split into train and val
train, val = train_test_split(subset, test_size=0.2, random_state=SEED)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

tensorboard = pl_loggers.TensorBoardLogger(save_dir=LOG_PATH, name=LOG_NAME_EXPERIMENT_2)
trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True, logger=tensorboard) #logger=None, 


model = MalwaresModelLinearLayer(input_size = subset.shape[1]-1, output_size = len(label_encoder.classes_), seed=SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [59]:
trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 288   
------------------------------------------------------------
288       Trainable params
0         Non-trainable params
288       Total params
0.001     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[  0,   0, 106,   0,   0,   0,   0,   0,   0],
        [ 27,   0,  80,   0,   0,   0,   0,   0,   0],
        [  0,   0,  82,   0,  11,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 118],
        [  0,   0,  70,   0,   0,   0,  27,   1,   0],
        [  0,   0,  98,   0,  17,   0,   0,   0,   0],
        [  5,   0,  13,   0,  56,   0,   0,   0,  53],
        [  1,   0,  30,   0,  32,   0,   0,   0,  47],
        [  0,   0, 125,   0,   1,   0,   0,   0,   0]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (35) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[ 664,    0,  931,    0,  875,   19,    0,    0,   17],
        [  76, 2027,  230,    0,    8,  170,    1,    0,    0],
        [ 326,    0,  657,    0, 1431,   77,    0,    0,    7],
        [   0,    2,    1,    9,    0,    0, 1675,    3,  823],
        [  35,    0,  584,    0, 1758,   18,   45,    2,   56],
        [   0,    2,  185,    0,  473, 1855,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 1122,  960,  178],
        [   3,   85,   54,    0,   95,    1, 1036, 1063,  173],
        [ 154,    0,  725,    0,  322,  110,    1,    0, 1204]])
Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[ 664,    0,  931,    0,  875,   19,    0,    0,   17],
        [  76, 2027,  230,    0,    8,  170,    1,    0,    0],
        [ 326,    0,  657,    0, 1431,   77,    0,    0,    7],
        [   0,    2,    1,    9,    0,    0, 1675,    3,  823],
        [  35,    0,  584,    0, 1758,   18,   45,    2,   

Metric Validation/Accuracy improved. New best score: 0.669


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[2479,    0, 1300,    0, 1012,   19,    0,    0,   96],
        [  76, 4432,  230,    0,    8,  170,    1,    0,    0],
        [1082,    0, 2049,    0, 1673,   79,    0,    0,   20],
        [   0,    2,    1, 1481,    0,    0, 2586,   15,  823],
        [  35,    0,  584,    0, 4148,   18,   45,    2,   66],
        [   0,    3,  185,    0,  473, 4254,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 1880, 2557,  178],
        [   3,   85,   54,    0,   95,    1, 1250, 3249,  173],
        [ 307,    0,  729,    0,  324,  110,    1,    0, 3435]])


Metric Validation/Accuracy improved by 0.225 >= min_delta = 0.0. New best score: 0.894


Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[2479,    0, 1300,    0, 1012,   19,    0,    0,   96],
        [  76, 4432,  230,    0,    8,  170,    1,    0,    0],
        [1082,    0, 2049,    0, 1673,   79,    0,    0,   20],
        [   0,    2,    1, 1481,    0,    0, 2586,   15,  823],
        [  35,    0,  584,    0, 4148,   18,   45,    2,   66],
        [   0,    3,  185,    0,  473, 4254,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 1880, 2557,  178],
        [   3,   85,   54,    0,   95,    1, 1250, 3249,  173],
        [ 307,    0,  729,    0,  324,  110,    1,    0, 3435]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[4415,    0, 1618,    0, 1020,   19,    0,    0,  234],
        [  76, 6837,  230,    0,    8,  170,    1,    0,    0],
        [1517,    0, 3988,    0, 1684,   79,    0,    0,   40],
        [   0,    2,    1, 3861,    0,    0, 2601,   15,  823],
        [  35,    0,  584,    0, 6539,   18,   45,    2,   75],
        [   0,    3,  185,    0,  473, 6654,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 3169, 3623,  178],
        [   3,   85,   54,    0,   95,    1, 1482, 5417,  173],
        [ 389,    0,  730,    0,  324,  110,    1,    0, 5742]])


Metric Validation/Accuracy improved by 0.037 >= min_delta = 0.0. New best score: 0.931


Epoch end: Train, epoch number: 2
TrainEpoch/CM
 tensor([[4415,    0, 1618,    0, 1020,   19,    0,    0,  234],
        [  76, 6837,  230,    0,    8,  170,    1,    0,    0],
        [1517,    0, 3988,    0, 1684,   79,    0,    0,   40],
        [   0,    2,    1, 3861,    0,    0, 2601,   15,  823],
        [  35,    0,  584,    0, 6539,   18,   45,    2,   75],
        [   0,    3,  185,    0,  473, 6654,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 3169, 3623,  178],
        [   3,   85,   54,    0,   95,    1, 1482, 5417,  173],
        [ 389,    0,  730,    0,  324,  110,    1,    0, 5742]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[6607,    0, 1699,    0, 1020,   19,    0,    0,  361],
        [  76, 9242,  230,    0,    8,  170,    1,    0,    0],
        [1973,    0, 5911,    0, 1686,   79,    0,    0,   64],
        [   0,    2,    1, 6256,    0,    0, 2601,   15,  823],
        [  35,    0,  584,    0, 8932,   18,   45,    2,   82],
        [   0,    3,  185,    0,  473, 9054,    0,    0,    0],
        [  10,   14,   22,    0,  176,    0, 4964, 4183,  178],
        [   3,   85,   54,    0,   95,    1, 1901, 7398,  173],
        [ 473,    0,  730,    0,  324,  110,    1,    0, 8048]])
Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[6607,    0, 1699,    0, 1020,   19,    0,    0,  361],
        [  76, 9242,  230,    0,    8,  170,    1,    0,    0],
        [1973,    0, 5911,    0, 1686,   79,    0,    0,   64],
        [   0,    2,    1, 6256,    0,    0, 2601,   15,  823],
        [  35,    0,  584,    0, 8932,   18,   45,    2,   

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[ 8844,     0,  1725,     0,  1020,    19,     0,     0,   498],
        [   76, 11647,   230,     0,     8,   170,     1,     0,     0],
        [ 2287,     0,  7978,     0,  1686,    79,     0,     0,    88],
        [    0,     2,     1,  8651,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 11327,    18,    45,     2,    87],
        [    0,     3,   185,     0,   473, 11454,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0,  6798,  4704,   178],
        [    3,    85,    54,     0,    95,     1,  2322,  9377,   173],
        [  553,     0,   730,     0,   324,   110,     1,     0, 10358]])
Epoch end: Train, epoch number: 4
TrainEpoch/CM
 tensor([[ 8844,     0,  1725,     0,  1020,    19,     0,     0,   498],
        [   76, 11647,   230,     0,     8,   170,     1,     0,     0],
        [ 2287,     0,  7978,     0,  1686,    79,     0,     0,    88],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[11102,     0,  1739,     0,  1020,    19,     0,     0,   626],
        [   76, 14052,   230,     0,     8,   170,     1,     0,     0],
        [ 2569,     0, 10075,     0,  1686,    79,     0,     0,   114],
        [    0,     2,     1, 11046,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 13722,    18,    45,     2,    92],
        [    0,     3,   185,     0,   473, 13854,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0,  8696,  5161,   178],
        [    3,    85,    54,     0,    95,     1,  2786, 11313,   173],
        [  636,     0,   730,     0,   324,   110,     1,     0, 12665]])
Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[11102,     0,  1739,     0,  1020,    19,     0,     0,   626],
        [   76, 14052,   230,     0,     8,   170,     1,     0,     0],
        [ 2569,     0, 10075,     0,  1686,    79,     0,     0,   114],
        [    0,

Metric Validation/Accuracy improved by 0.004 >= min_delta = 0.0. New best score: 0.935


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[13361,     0,  1753,     0,  1020,    19,     0,     0,   753],
        [   76, 16457,   230,     0,     8,   170,     1,     0,     0],
        [ 2808,     0, 12216,     0,  1686,    79,     0,     0,   139],
        [    0,     2,     1, 13441,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 16117,    18,    45,     2,    97],
        [    0,     3,   185,     0,   473, 16254,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 10584,  5628,   178],
        [    3,    85,    54,     0,    95,     1,  3256, 13243,   173],
        [  718,     0,   730,     0,   324,   110,     1,     0, 14973]])
Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[13361,     0,  1753,     0,  1020,    19,     0,     0,   753],
        [   76, 16457,   230,     0,     8,   170,     1,     0,     0],
        [ 2808,     0, 12216,     0,  1686,    79,     0,     0,   139],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[15621,     0,  1763,     0,  1020,    19,     0,     0,   883],
        [   76, 18862,   230,     0,     8,   170,     1,     0,     0],
        [ 3040,     0, 14369,     0,  1686,    79,     0,     0,   159],
        [    0,     2,     1, 15836,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 18513,    18,    45,     2,   101],
        [    0,     3,   185,     0,   473, 18654,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 12470,  6097,   178],
        [    3,    85,    54,     0,    95,     1,  3735, 15164,   173],
        [  801,     0,   730,     0,   324,   110,     1,     0, 17280]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[15621,     0,  1763,     0,  1020,    19,     0,     0,   883],
        [   76, 18862,   230,     0,     8,   170,     1,     0,     0],
        [ 3040,     0, 14369,     0,  1686,    79,     0,     0,   159],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[17889,     0,  1773,     0,  1020,    19,     0,     0,  1005],
        [   76, 21267,   230,     0,     8,   170,     1,     0,     0],
        [ 3245,     0, 16547,     0,  1686,    79,     0,     0,   181],
        [    0,     2,     1, 18231,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 20910,    18,    45,     2,   104],
        [    0,     3,   185,     0,   473, 21054,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 14416,  6506,   178],
        [    3,    85,    54,     0,    95,     1,  4232, 17067,   173],
        [  883,     0,   730,     0,   324,   110,     1,     0, 19588]])
Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[17889,     0,  1773,     0,  1020,    19,     0,     0,  1005],
        [   76, 21267,   230,     0,     8,   170,     1,     0,     0],
        [ 3245,     0, 16547,     0,  1686,    79,     0,     0,   181],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[20156,     0,  1783,     0,  1020,    19,     0,     0,  1128],
        [   76, 23672,   230,     0,     8,   170,     1,     0,     0],
        [ 3442,     0, 18730,     0,  1686,    79,     0,     0,   206],
        [    0,     2,     1, 20626,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 23310,    18,    45,     2,   104],
        [    0,     3,   185,     0,   473, 23454,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 16349,  6928,   178],
        [    3,    85,    54,     0,    95,     1,  4712, 18987,   173],
        [  966,     0,   730,     0,   324,   110,     1,     0, 21895]])
Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[20156,     0,  1783,     0,  1020,    19,     0,     0,  1128],
        [   76, 23672,   230,     0,     8,   170,     1,     0,     0],
        [ 3442,     0, 18730,     0,  1686,    79,     0,     0,   206],
        [    0

Metric Validation/Accuracy improved by 0.002 >= min_delta = 0.0. New best score: 0.937


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[22422,     0,  1793,     0,  1020,    19,     0,     0,  1252],
        [   76, 26077,   230,     0,     8,   170,     1,     0,     0],
        [ 3610,     0, 20943,     0,  1686,    79,     0,     0,   230],
        [    0,     2,     1, 23021,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 25709,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 25854,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 18312,  7320,   178],
        [    3,    85,    54,     0,    95,     1,  5213, 20886,   173],
        [ 1048,     0,   730,     0,   324,   110,     1,     0, 24203]])
Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[22422,     0,  1793,     0,  1020,    19,     0,     0,  1252],
        [   76, 26077,   230,     0,     8,   170,     1,     0,     0],
        [ 3610,     0, 20943,     0,  1686,    79,     0,     0,   230],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[24692,     0,  1803,     0,  1020,    19,     0,     0,  1372],
        [   76, 28482,   230,     0,     8,   170,     1,     0,     0],
        [ 3763,     0, 23173,     0,  1686,    79,     0,     0,   252],
        [    0,     2,     1, 25416,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 28109,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 28254,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 20272,  7715,   178],
        [    3,    85,    54,     0,    95,     1,  5685, 22814,   173],
        [ 1132,     0,   730,     0,   324,   110,     1,     0, 26509]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[24692,     0,  1803,     0,  1020,    19,     0,     0,  1372],
        [   76, 28482,   230,     0,     8,   170,     1,     0,     0],
        [ 3763,     0, 23173,     0,  1686,    79,     0,     0,   252],
        [    

Metric Validation/Accuracy improved by 0.000 >= min_delta = 0.0. New best score: 0.938


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[26962,     0,  1813,     0,  1020,    19,     0,     0,  1492],
        [   76, 30887,   230,     0,     8,   170,     1,     0,     0],
        [ 3899,     0, 25420,     0,  1686,    79,     0,     0,   274],
        [    0,     2,     1, 27811,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 30509,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 30654,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 22273,  8069,   178],
        [    3,    85,    54,     0,    95,     1,  6172, 24727,   173],
        [ 1215,     0,   730,     0,   324,   110,     1,     0, 28816]])
Epoch end: Train, epoch number: 12
TrainEpoch/CM
 tensor([[26962,     0,  1813,     0,  1020,    19,     0,     0,  1492],
        [   76, 30887,   230,     0,     8,   170,     1,     0,     0],
        [ 3899,     0, 25420,     0,  1686,    79,     0,     0,   274],
        [    

Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.944


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[29233,     0,  1823,     0,  1020,    19,     0,     0,  1611],
        [   76, 33292,   230,     0,     8,   170,     1,     0,     0],
        [ 4024,     0, 27682,     0,  1686,    79,     0,     0,   292],
        [    0,     2,     1, 30206,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 32909,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 33054,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 24282,  8415,   178],
        [    3,    85,    54,     0,    95,     1,  6655, 26644,   173],
        [ 1295,     0,   730,     0,   324,   110,     1,     0, 31126]])
Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[29233,     0,  1823,     0,  1020,    19,     0,     0,  1611],
        [   76, 33292,   230,     0,     8,   170,     1,     0,     0],
        [ 4024,     0, 27682,     0,  1686,    79,     0,     0,   292],
        [    

Metric Validation/Accuracy improved by 0.003 >= min_delta = 0.0. New best score: 0.947


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[31507,     0,  1833,     0,  1020,    19,     0,     0,  1727],
        [   76, 35697,   230,     0,     8,   170,     1,     0,     0],
        [ 4152,     0, 29941,     0,  1686,    79,     0,     0,   310],
        [    0,     2,     1, 32601,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 35309,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 35454,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 26291,  8761,   178],
        [    3,    85,    54,     0,    95,     1,  7133, 28566,   173],
        [ 1378,     0,   730,     0,   324,   110,     1,     0, 33433]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[31507,     0,  1833,     0,  1020,    19,     0,     0,  1727],
        [   76, 35697,   230,     0,     8,   170,     1,     0,     0],
        [ 4152,     0, 29941,     0,  1686,    79,     0,     0,   310],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 16
ValidationEpoch/CM
 tensor([[33783,     0,  1843,     0,  1020,    19,     0,     0,  1841],
        [   76, 38102,   230,     0,     8,   170,     1,     0,     0],
        [ 4271,     0, 32209,     0,  1686,    79,     0,     0,   328],
        [    0,     2,     1, 34996,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 37709,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 37854,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 28311,  9096,   178],
        [    3,    85,    54,     0,    95,     1,  7610, 30489,   173],
        [ 1459,     0,   730,     0,   324,   110,     1,     0, 35742]])
Epoch end: Train, epoch number: 15
TrainEpoch/CM
 tensor([[33783,     0,  1843,     0,  1020,    19,     0,     0,  1841],
        [   76, 38102,   230,     0,     8,   170,     1,     0,     0],
        [ 4271,     0, 32209,     0,  1686,    79,     0,     0,   328],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 17
ValidationEpoch/CM
 tensor([[36064,     0,  1853,     0,  1020,    19,     0,     0,  1950],
        [   76, 40507,   230,     0,     8,   170,     1,     0,     0],
        [ 4405,     0, 34467,     0,  1686,    79,     0,     0,   341],
        [    0,     2,     1, 37391,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 40109,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 40254,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 30333,  9429,   178],
        [    3,    85,    54,     0,    95,     1,  8098, 32401,   173],
        [ 1544,     0,   730,     0,   324,   110,     1,     0, 38047]])
Epoch end: Train, epoch number: 16
TrainEpoch/CM
 tensor([[36064,     0,  1853,     0,  1020,    19,     0,     0,  1950],
        [   76, 40507,   230,     0,     8,   170,     1,     0,     0],
        [ 4405,     0, 34467,     0,  1686,    79,     0,     0,   341],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 18
ValidationEpoch/CM
 tensor([[38353,     0,  1863,     0,  1020,    19,     0,     0,  2051],
        [   76, 42912,   230,     0,     8,   170,     1,     0,     0],
        [ 4533,     0, 36732,     0,  1686,    79,     0,     0,   353],
        [    0,     2,     1, 39786,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 42509,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 42654,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 32364,  9753,   178],
        [    3,    85,    54,     0,    95,     1,  8554, 34345,   173],
        [ 1629,     0,   730,     0,   324,   110,     1,     0, 40352]])
Epoch end: Train, epoch number: 17
TrainEpoch/CM
 tensor([[38353,     0,  1863,     0,  1020,    19,     0,     0,  2051],
        [   76, 42912,   230,     0,     8,   170,     1,     0,     0],
        [ 4533,     0, 36732,     0,  1686,    79,     0,     0,   353],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 19
ValidationEpoch/CM
 tensor([[40636,     0,  1873,     0,  1020,    19,     0,     0,  2158],
        [   76, 45317,   230,     0,     8,   170,     1,     0,     0],
        [ 4641,     0, 39019,     0,  1686,    79,     0,     0,   363],
        [    0,     2,     1, 42181,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 44909,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 45054,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 34380, 10092,   178],
        [    3,    85,    54,     0,    95,     1,  9005, 36294,   173],
        [ 1714,     0,   730,     0,   324,   110,     1,     0, 42657]])


Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 0.947. Signaling Trainer to stop.


Epoch end: Train, epoch number: 18
TrainEpoch/CM
 tensor([[40636,     0,  1873,     0,  1020,    19,     0,     0,  2158],
        [   76, 45317,   230,     0,     8,   170,     1,     0,     0],
        [ 4641,     0, 39019,     0,  1686,    79,     0,     0,   363],
        [    0,     2,     1, 42181,     0,     0,  2601,    15,   823],
        [   35,     0,   584,     0, 44909,    18,    45,     2,   105],
        [    0,     3,   185,     0,   473, 45054,     0,     0,     0],
        [   10,    14,    22,     0,   176,     0, 34380, 10092,   178],
        [    3,    85,    54,     0,    95,     1,  9005, 36294,   173],
        [ 1714,     0,   730,     0,   324,   110,     1,     0, 42657]])


In [60]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelLinearLayer.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = subset.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/official_logs/single-layer_30_from_rp4_weights_30s_Xi_sensor_1_rp3/version_0/checkpoints/epoch=13-step=490.ckpt
tensor(0.9466, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[452,   0,   4,   0,   0,   0,   0,   0,  24],
        [  0, 474,   0,   0,   0,   0,   0,   0,   0],
        [ 18,   0, 460,   0,   0,   0,   0,   0,   1],
        [  0,   0,   0, 462,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 485,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 478,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0, 415,  67,   0],
        [  0,   0,   0,   0,   0,   0,  97, 388,   0],
        [ 22,   0,   0,   0,   0,   0,   0,   0, 463]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.9466128349304199
      Test/F1Score          0.9464346170425415
        Test/Loss            0.304229736328125
     Test/Precision         0.

[{'Test/Loss': 0.304229736328125,
  'Test/Accuracy': 0.9466128349304199,
  'Test/Precision': 0.9474481344223022,
  'Test/Recall': 0.9466128349304199,
  'Test/F1Score': 0.9464346170425415,
  'TestEpoch/Accuracy': 0.946403980255127,
  'TestEpoch/Precision': 0.9469047784805298,
  'TestEpoch/Recall': 0.946403980255127,
  'TestEpoch/F1Score': 0.9464320540428162}]

In [61]:
sys.path.append(str(repo_base_path  / "training"))

In [62]:
# tensorboard = pl_loggers.TensorBoardLogger('./')

from mlp import MalwaresModelMLP

# split into train and val
train, val = train_test_split(subset, test_size=0.2, random_state=SEED)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

tensorboard = pl_loggers.TensorBoardLogger(save_dir=LOG_PATH, name=LOG_NAME_EXPERIMENT_3)
trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True, logger=tensorboard) #logger=None, 


model = MalwaresModelMLP(input_size = subset.shape[1]-1, output_size = len(label_encoder.classes_), seed=SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [63]:

trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 960   
6 | l2            | Linear                    | 930   
7 | l3            | Linear                    | 279   
------------------------------------------------------------
2.2 K     Trainable params
0         Non-trainable params
2.2 K     Total params
0.009     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[  0,   0, 106,   0,   0,   0,   0,   0,   0],
        [  0,   0,  96,   0,   0,   0,  11,   0,   0],
        [  0,   0,  91,   0,   0,   0,   2,   0,   0],
        [  0,   0, 118,   0,   0,   0,   0,   0,   0],
        [  0,   0,  98,   0,   0,   0,   0,   0,   0],
        [  0,   0, 106,   0,   0,   0,   9,   0,   0],
        [  0,   0,  80,   0,   0,   0,  47,   0,   0],
        [  0,   0,  92,   0,   0,   0,  18,   0,   0],
        [  0,   0, 126,   0,   0,   0,   0,   0,   0]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (35) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[ 313,    0,  911,    0, 1178,    0,    0,    0,  104],
        [   0, 2229,  210,    0,    0,    0,   73,    0,    0],
        [ 157,    0, 1012,    0, 1233,    6,    4,    0,   86],
        [   0,    0,  340, 1234,    0,    0,  426,  513,    0],
        [  26,    0,  671,    0, 1799,    0,    0,    0,    2],
        [   0,  178,  270,    0,  322, 1631,  110,    0,    4],
        [   0,    0,  114,    0,    0,    0, 1049, 1319,    0],
        [   0,    0,  135,    0,    0,    0,  944, 1431,    0],
        [  45,    0,  333,    0,  734,   61,    0,    0, 1343]])
Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[ 313,    0,  911,    0, 1178,    0,    0,    0,  104],
        [   0, 2229,  210,    0,    0,    0,   73,    0,    0],
        [ 157,    0, 1012,    0, 1233,    6,    4,    0,   86],
        [   0,    0,  340, 1234,    0,    0,  426,  513,    0],
        [  26,    0,  671,    0, 1799,    0,    0,    0,   

Metric Validation/Accuracy improved. New best score: 0.723


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[2334,    0, 1015,    0, 1297,    0,    0,    0,  260],
        [   0, 4634,  210,    0,    0,    0,   73,    0,    0],
        [ 254,    0, 3084,    0, 1409,    8,    4,    0,  144],
        [   0,    0,  340, 3629,    0,    0,  426,  513,    0],
        [  32,    0,  731,    0, 4133,    0,    0,    0,    2],
        [   0,  178,  270,    0,  322, 4031,  110,    0,    4],
        [   0,    0,  114,    0,    0,    0, 2402, 2321,    0],
        [   0,    0,  135,    0,    0,    0, 1459, 3316,    0],
        [ 138,    0,  342,    0,  734,   61,    0,    0, 3631]])
Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[2334,    0, 1015,    0, 1297,    0,    0,    0,  260],
        [   0, 4634,  210,    0,    0,    0,   73,    0,    0],
        [ 254,    0, 3084,    0, 1409,    8,    4,    0,  144],
        [   0,    0,  340, 3629,    0,    0,  426,  513,    0],
        [  32,    0,  731,    0, 4133,    0,    0,    0,   

Metric Validation/Accuracy improved by 0.213 >= min_delta = 0.0. New best score: 0.937


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[4650,    0, 1021,    0, 1299,    0,    0,    0,  336],
        [   0, 7039,  210,    0,    0,    0,   73,    0,    0],
        [ 278,    0, 5447,    0, 1415,   11,    4,    0,  153],
        [   0,    0,  340, 6024,    0,    0,  426,  513,    0],
        [  37,    0,  737,    0, 6522,    0,    0,    0,    2],
        [   0,  178,  270,    0,  322, 6431,  110,    0,    4],
        [   0,    0,  114,    0,    0,    0, 4376, 2702,    0],
        [   0,    0,  135,    0,    0,    0, 1835, 5340,    0],
        [ 227,    0,  352,    0,  734,   61,    0,    0, 5922]])
Epoch end: Train, epoch number: 2
TrainEpoch/CM
 tensor([[4650,    0, 1021,    0, 1299,    0,    0,    0,  336],
        [   0, 7039,  210,    0,    0,    0,   73,    0,    0],
        [ 278,    0, 5447,    0, 1415,   11,    4,    0,  153],
        [   0,    0,  340, 6024,    0,    0,  426,  513,    0],
        [  37,    0,  737,    0, 6522,    0,    0,    0,   

Metric Validation/Accuracy improved by 0.021 >= min_delta = 0.0. New best score: 0.958


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[6977,    0, 1027,    0, 1299,    0,    0,    0,  403],
        [   0, 9444,  210,    0,    0,    0,   73,    0,    0],
        [ 296,    0, 7826,    0, 1418,   11,    4,    0,  158],
        [   0,    0,  340, 8419,    0,    0,  426,  513,    0],
        [  38,    0,  738,    0, 8920,    0,    0,    0,    2],
        [   0,  178,  270,    0,  322, 8831,  110,    0,    4],
        [   0,    0,  114,    0,    0,    0, 6464, 2969,    0],
        [   0,    0,  135,    0,    0,    0, 2146, 7429,    0],
        [ 289,    0,  361,    0,  734,   61,    0,    0, 8241]])
Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[6977,    0, 1027,    0, 1299,    0,    0,    0,  403],
        [   0, 9444,  210,    0,    0,    0,   73,    0,    0],
        [ 296,    0, 7826,    0, 1418,   11,    4,    0,  158],
        [   0,    0,  340, 8419,    0,    0,  426,  513,    0],
        [  38,    0,  738,    0, 8920,    0,    0,    0,   

Metric Validation/Accuracy improved by 0.007 >= min_delta = 0.0. New best score: 0.965


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[ 9317,     0,  1033,     0,  1299,     0,     0,     0,   457],
        [    0, 11849,   210,     0,     0,     0,    73,     0,     0],
        [  307,     0, 10217,     0,  1419,    12,     4,     0,   159],
        [    0,     0,   340, 10814,     0,     0,   426,   513,     0],
        [   38,     0,   738,     0, 11320,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 11231,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0,  8571,  3217,     0],
        [    0,     0,   135,     0,     0,     0,  2448,  9527,     0],
        [  335,     0,   370,     0,   734,    61,     0,     0, 10576]])


Metric Validation/Accuracy improved by 0.005 >= min_delta = 0.0. New best score: 0.970


Epoch end: Train, epoch number: 4
TrainEpoch/CM
 tensor([[ 9317,     0,  1033,     0,  1299,     0,     0,     0,   457],
        [    0, 11849,   210,     0,     0,     0,    73,     0,     0],
        [  307,     0, 10217,     0,  1419,    12,     4,     0,   159],
        [    0,     0,   340, 10814,     0,     0,   426,   513,     0],
        [   38,     0,   738,     0, 11320,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 11231,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0,  8571,  3217,     0],
        [    0,     0,   135,     0,     0,     0,  2448,  9527,     0],
        [  335,     0,   370,     0,   734,    61,     0,     0, 10576]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[11639,     0,  1043,     0,  1299,     0,     0,     0,   525],
        [    0, 14254,   210,     0,     0,     0,    73,     0,     0],
        [  324,     0, 12599,     0,  1420,    12,     4,     0,   164],
        [    0,     0,   340, 13209,     0,     0,   426,   513,     0],
        [   38,     0,   738,     0, 13720,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 13631,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 10655,  3488,     0],
        [    0,     0,   135,     0,     0,     0,  2613, 11762,     0],
        [  378,     0,   380,     0,   734,    61,     0,     0, 12913]])
Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[11639,     0,  1043,     0,  1299,     0,     0,     0,   525],
        [    0, 14254,   210,     0,     0,     0,    73,     0,     0],
        [  324,     0, 12599,     0,  1420,    12,     4,     0,   164],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[13977,     0,  1048,     0,  1299,     0,     0,     0,   582],
        [    0, 16659,   210,     0,     0,     0,    73,     0,     0],
        [  345,     0, 14979,     0,  1420,    12,     4,     0,   168],
        [    0,     0,   340, 15604,     0,     0,   426,   513,     0],
        [   42,     0,   738,     0, 16116,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 16031,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 12800,  3698,     0],
        [    0,     0,   135,     0,     0,     0,  2777, 13998,     0],
        [  428,     0,   383,     0,   734,    61,     0,     0, 15250]])


Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.976


Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[13977,     0,  1048,     0,  1299,     0,     0,     0,   582],
        [    0, 16659,   210,     0,     0,     0,    73,     0,     0],
        [  345,     0, 14979,     0,  1420,    12,     4,     0,   168],
        [    0,     0,   340, 15604,     0,     0,   426,   513,     0],
        [   42,     0,   738,     0, 16116,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 16031,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 12800,  3698,     0],
        [    0,     0,   135,     0,     0,     0,  2777, 13998,     0],
        [  428,     0,   383,     0,   734,    61,     0,     0, 15250]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[16309,     0,  1054,     0,  1299,     0,     0,     0,   644],
        [    0, 19064,   210,     0,     0,     0,    73,     0,     0],
        [  361,     0, 17362,     0,  1422,    12,     4,     0,   172],
        [    0,     0,   340, 17999,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 18515,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 18431,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 14996,  3857,     0],
        [    0,     0,   135,     0,     0,     0,  2886, 16289,     0],
        [  470,     0,   386,     0,   734,    61,     0,     0, 17595]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[16309,     0,  1054,     0,  1299,     0,     0,     0,   644],
        [    0, 19064,   210,     0,     0,     0,    73,     0,     0],
        [  361,     0, 17362,     0,  1422,    12,     4,     0,   172],
        [    0,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[18652,     0,  1060,     0,  1299,     0,     0,     0,   695],
        [    0, 21469,   210,     0,     0,     0,    73,     0,     0],
        [  377,     0, 19749,     0,  1422,    12,     4,     0,   174],
        [    0,     0,   340, 20394,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 20915,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 20831,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 17202,  4006,     0],
        [    0,     0,   135,     0,     0,     0,  3047, 18528,     0],
        [  511,     0,   388,     0,   734,    61,     0,     0, 19942]])


Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.982


Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[18652,     0,  1060,     0,  1299,     0,     0,     0,   695],
        [    0, 21469,   210,     0,     0,     0,    73,     0,     0],
        [  377,     0, 19749,     0,  1422,    12,     4,     0,   174],
        [    0,     0,   340, 20394,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 20915,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 20831,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 17202,  4006,     0],
        [    0,     0,   135,     0,     0,     0,  3047, 18528,     0],
        [  511,     0,   388,     0,   734,    61,     0,     0, 19942]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[20997,     0,  1068,     0,  1299,     0,     0,     0,   742],
        [    0, 23874,   210,     0,     0,     0,    73,     0,     0],
        [  388,     0, 22142,     0,  1423,    12,     4,     0,   174],
        [    0,     0,   340, 22789,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 23315,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 23231,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 19443,  4120,     0],
        [    0,     0,   135,     0,     0,     0,  3168, 20807,     0],
        [  542,     0,   393,     0,   734,    61,     0,     0, 22296]])
Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[20997,     0,  1068,     0,  1299,     0,     0,     0,   742],
        [    0, 23874,   210,     0,     0,     0,    73,     0,     0],
        [  388,     0, 22142,     0,  1423,    12,     4,     0,   174],
        [    0

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[23352,     0,  1074,     0,  1299,     0,     0,     0,   781],
        [    0, 26279,   210,     0,     0,     0,    73,     0,     0],
        [  399,     0, 24534,     0,  1423,    12,     4,     0,   176],
        [    0,     0,   340, 25184,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 25715,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 25631,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 21674,  4244,     0],
        [    0,     0,   135,     0,     0,     0,  3278, 23097,     0],
        [  576,     0,   397,     0,   734,    61,     0,     0, 24648]])


Metric Validation/Accuracy improved by 0.002 >= min_delta = 0.0. New best score: 0.984


Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[23352,     0,  1074,     0,  1299,     0,     0,     0,   781],
        [    0, 26279,   210,     0,     0,     0,    73,     0,     0],
        [  399,     0, 24534,     0,  1423,    12,     4,     0,   176],
        [    0,     0,   340, 25184,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 25715,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 25631,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 21674,  4244,     0],
        [    0,     0,   135,     0,     0,     0,  3278, 23097,     0],
        [  576,     0,   397,     0,   734,    61,     0,     0, 24648]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[25692,     0,  1080,     0,  1299,     0,     0,     0,   835],
        [    0, 28684,   210,     0,     0,     0,    73,     0,     0],
        [  408,     0, 26929,     0,  1423,    12,     4,     0,   177],
        [    0,     0,   340, 27579,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 28115,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 28031,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 23934,  4339,     0],
        [    0,     0,   135,     0,     0,     0,  3364, 25411,     0],
        [  601,     0,   399,     0,   734,    61,     0,     0, 27011]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[25692,     0,  1080,     0,  1299,     0,     0,     0,   835],
        [    0, 28684,   210,     0,     0,     0,    73,     0,     0],
        [  408,     0, 26929,     0,  1423,    12,     4,     0,   177],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[28026,     0,  1092,     0,  1299,     0,     0,     0,   889],
        [    0, 31089,   210,     0,     0,     0,    73,     0,     0],
        [  432,     0, 29301,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 29974,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 30515,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 30431,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 26211,  4417,     0],
        [    0,     0,   135,     0,     0,     0,  3444, 27731,     0],
        [  642,     0,   403,     0,   734,    61,     0,     0, 29356]])


Metric Validation/Accuracy improved by 0.002 >= min_delta = 0.0. New best score: 0.986


Epoch end: Train, epoch number: 12
TrainEpoch/CM
 tensor([[28026,     0,  1092,     0,  1299,     0,     0,     0,   889],
        [    0, 31089,   210,     0,     0,     0,    73,     0,     0],
        [  432,     0, 29301,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 29974,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 30515,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 30431,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 26211,  4417,     0],
        [    0,     0,   135,     0,     0,     0,  3444, 27731,     0],
        [  642,     0,   403,     0,   734,    61,     0,     0, 29356]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[30383,     0,  1097,     0,  1299,     0,     0,     0,   927],
        [    0, 33494,   210,     0,     0,     0,    73,     0,     0],
        [  442,     0, 31696,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 32369,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 32915,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 32831,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 28477,  4506,     0],
        [    0,     0,   135,     0,     0,     0,  3542, 30033,     0],
        [  671,     0,   405,     0,   734,    61,     0,     0, 31715]])
Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[30383,     0,  1097,     0,  1299,     0,     0,     0,   927],
        [    0, 33494,   210,     0,     0,     0,    73,     0,     0],
        [  442,     0, 31696,     0,  1425,    12,     4,     0,   184],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[32739,     0,  1104,     0,  1299,     0,     0,     0,   964],
        [    0, 35899,   210,     0,     0,     0,    73,     0,     0],
        [  454,     0, 34089,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 34764,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 35315,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 35231,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 30745,  4593,     0],
        [    0,     0,   135,     0,     0,     0,  3634, 32341,     0],
        [  705,     0,   408,     0,   734,    61,     0,     0, 34068]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[32739,     0,  1104,     0,  1299,     0,     0,     0,   964],
        [    0, 35899,   210,     0,     0,     0,    73,     0,     0],
        [  454,     0, 34089,     0,  1425,    12,     4,     0,   184],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 16
ValidationEpoch/CM
 tensor([[35112,     0,  1109,     0,  1299,     0,     0,     0,   986],
        [    0, 38304,   210,     0,     0,     0,    73,     0,     0],
        [  464,     0, 36484,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 37159,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 37715,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 37631,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 33012,  4681,     0],
        [    0,     0,   135,     0,     0,     0,  3722, 34653,     0],
        [  742,     0,   411,     0,   734,    61,     0,     0, 36418]])
Epoch end: Train, epoch number: 15
TrainEpoch/CM
 tensor([[35112,     0,  1109,     0,  1299,     0,     0,     0,   986],
        [    0, 38304,   210,     0,     0,     0,    73,     0,     0],
        [  464,     0, 36484,     0,  1425,    12,     4,     0,   184],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 17
ValidationEpoch/CM
 tensor([[37476,     0,  1112,     0,  1301,     0,     0,     0,  1017],
        [    0, 40709,   210,     0,     0,     0,    73,     0,     0],
        [  477,     0, 38876,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 39554,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 40115,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 40031,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 35261,  4787,     0],
        [    0,     0,   135,     0,     0,     0,  3792, 36983,     0],
        [  771,     0,   411,     0,   734,    61,     0,     0, 38779]])
Epoch end: Train, epoch number: 16
TrainEpoch/CM
 tensor([[37476,     0,  1112,     0,  1301,     0,     0,     0,  1017],
        [    0, 40709,   210,     0,     0,     0,    73,     0,     0],
        [  477,     0, 38876,     0,  1425,    12,     4,     0,   184],
        [    

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 18
ValidationEpoch/CM
 tensor([[39834,     0,  1120,     0,  1301,     0,     0,     0,  1051],
        [    0, 43114,   210,     0,     0,     0,    73,     0,     0],
        [  487,     0, 41271,     0,  1425,    12,     4,     0,   184],
        [    0,     0,   340, 41949,     0,     0,   426,   513,     0],
        [   43,     0,   738,     0, 42515,     0,     0,     0,     2],
        [    0,   178,   270,     0,   322, 42431,   110,     0,     4],
        [    0,     0,   114,     0,     0,     0, 37536,  4867,     0],
        [    0,     0,   135,     0,     0,     0,  3867, 39308,     0],
        [  796,     0,   414,     0,   734,    61,     0,     0, 41141]])
Epoch end: Train, epoch number: 17
TrainEpoch/CM
 tensor([[39834,     0,  1120,     0,  1301,     0,     0,     0,  1051],
        [    0, 43114,   210,     0,     0,     0,    73,     0,     0],
        [  487,     0, 41271,     0,  1425,    12,     4,     0,   184],
        [    

Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 0.986. Signaling Trainer to stop.


In [64]:

print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelMLP.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = subset.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/official_logs/multi-layer_30_from_rp4_weights_30s_Xi_sensor_1_rp3/version_0/checkpoints/epoch=12-step=455.ckpt
tensor(0.9859, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[469,   0,   3,   0,   0,   0,   0,   0,   8],
        [  0, 474,   0,   0,   0,   0,   0,   0,   0],
        [  1,   0, 478,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0, 462,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 485,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 478,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0, 465,  17,   0],
        [  0,   0,   0,   0,   0,   0,  23, 462,   0],
        [  8,   0,   0,   0,   0,   0,   0,   0, 477]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.9858713150024414
      Test/F1Score          0.9861435890197754
        Test/Loss          0.038981132209300995
     Test/Precision         0

[{'Test/Loss': 0.038981132209300995,
  'Test/Accuracy': 0.9858713150024414,
  'Test/Precision': 0.9867787957191467,
  'Test/Recall': 0.9858713150024414,
  'Test/F1Score': 0.9861435890197754,
  'TestEpoch/Accuracy': 0.9862009286880493,
  'TestEpoch/Precision': 0.9862020015716553,
  'TestEpoch/Recall': 0.9862009286880493,
  'TestEpoch/F1Score': 0.9861922860145569}]

In [65]:
subset.columns.to_frame().to_csv(f"weight_selected_{TIME_WINDOW}.csv", index=False)