# Idea
Do some training

In [7]:
from pathlib import Path

import numpy as np
import pandas as pd
import pickle

In [8]:
import sys
repo_base_path = Path("./../").resolve()
assert str(repo_base_path).endswith("csg_is"), f"{repo_base_path} is not a valid path to the CSG_IS repository" 

sys.path.append(str(repo_base_path))

# from py_dataset import get_all_files_df
# from py_dataset import read_in_files
from py_dataset import feature_plotting
# from py_dataset import feature_selection
# from py_dataset import net_feature_engineering
# from py_dataset import entropy_feature_engineering
# from py_dataset.classes import DataSource
from py_dataset import sys_func



In [9]:
df = pd.read_csv('all_df_top34.csv')
df.set_index("timestamp", inplace=True)

In [10]:
df["label"].unique()

array(['1_normal', nan, '2_ransomware', '3_thetick', '4_bashlite',
       '5_httpbackdoor', '6_beurk', '7_backdoor', '8_bdvl', '9_xmrig'],
      dtype=object)

### Preprocessings
- remove Null values
- drop timestamp
- labelEncode
- normalize

In [11]:
print(df.shape)
old_df = df.copy()
df.dropna(axis=0, how='any', inplace=True)

print(df.shape)

(29427, 34)
(20345, 34)


In [12]:
df.reset_index(inplace=True, drop=True)

In [13]:
label_encoder = sys_func.create_label_encoder_for_labels()
df['label'] = label_encoder.transform(df['label'])

In [14]:
df = feature_plotting.test_transform_all_to_numeric_columns(df)

In [15]:
cols_to_exclude_from_scaling = ["label"]
vectors = feature_plotting.minmax_scale_features(df,remove_outliers_iqr_all_columns=False,
                                                        cols_to_exclude_from_scaling=cols_to_exclude_from_scaling)
# print(vectors.shape)
# print(" with dropped null: ", vectors.dropna(axis=0, how='any', inplace=False).shape)

In [16]:
df["label"].unique(), vectors["label"].unique()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

### Setup

In [17]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomeDataset(Dataset):
    def __init__(self, some_df:pd.DataFrame):
        
        self.x = torch.tensor(some_df.drop(columns=["label"], inplace=False).values, dtype=torch.float32)
        self.labels = torch.tensor(some_df["label"].values, dtype=torch.uint8)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        # if torch.is_tensor(idx):
        #     idx = idx.tolist()
        # print(self.x[idx], self.labels[idx])
        return self.x[idx], self.labels[idx]

In [18]:
from mlp import MalwaresModelMLP
from torch.utils.data import DataLoader
import lightning
from sklearn.model_selection import train_test_split
from lightning import loggers as pl_loggers
from lightning.pytorch.callbacks.early_stopping import EarlyStopping
from lightning.pytorch.callbacks.model_checkpoint import ModelCheckpoint

# tensorboard = pl_loggers.TensorBoardLogger('./')

# split into train and val
train, val = train_test_split(vectors, test_size=0.2)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True) #logger=None, 


model = MalwaresModelMLP(input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [19]:
trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 1.0 K 
6 | l2            | Linear                    | 930   
7 | l3            | Linear                    | 279   
------------------------------------------------------------
2.2 K     Trainable params
0         Non-trainable params
2.2 K     Total params
0.009     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[  0,   0,   0,   0,   0,   0,   0,  89,   0],
        [  0,   0,   0,   0,   0,  90,   0,  28,   0],
        [  0,   0,   0,   0,   0,   1,   0, 188,   0],
        [  0,   0,   0,   0,   0,   2,   0,  90,   0],
        [  0,   0,   0,   0,   0,   0,   0, 111,   0],
        [  0,   0,   0,   0,   0,   0,   0, 108,   0],
        [  0,   0,   0,   0,   0,   0,   0, 105,   0],
        [  0,   0,   0,   0,   0,   1,   0, 106,   0],
        [  0,   0,   0,   0,   0,   4,   0,  77,   0]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (33) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[   0,  206, 1353,    0,  178,  102,    0,  266,    0],
        [   0, 2073,    0,    0,    0,  130,    0,   90,    0],
        [   0,  368, 2173,    0,  330,  276,    0,  536,    0],
        [   0,  201, 1465,    0,  132,   73,    0,  314,    0],
        [   0,  266, 1263,    0,  162,  216,    0,  304,    0],
        [   0,  278, 1184,    0,   83,  373,    0,  295,    0],
        [   0,  222, 1321,    0,  164,  174,    0,  312,    0],
        [   0,  249, 1189,    0,   61,  382,    0,  356,    0],
        [   0,    0,    0,    0,    1,    6,    0,  218, 2000]])
Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[   0,  206, 1353,    0,  178,  102,    0,  266,    0],
        [   0, 2073,    0,    0,    0,  130,    0,   90,    0],
        [   0,  368, 2173,    0,  330,  276,    0,  536,    0],
        [   0,  201, 1465,    0,  132,   73,    0,  314,    0],
        [   0,  266, 1263,    0,  162,  216,    0,  304,   

Metric Validation/Accuracy improved. New best score: 0.372


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[  39,  206, 2855,  279,  193,  185,    0,  364,    0],
        [   0, 4246,    0,    0,    0,  132,    0,   90,    0],
        [  30,  378, 4811,  250,  363,  571,    0,  774,    0],
        [  60,  201, 2975,  339,  150,  153,    0,  400,    0],
        [  18,  266, 2731,  116,  182,  483,    0,  515,    0],
        [   1,  279, 1948,   15,   95, 1207,    0,  773,    0],
        [  20,  222, 2811,  154,  176,  405,    0,  493,    0],
        [   4,  249, 1636,   22,   71,  893,    0, 1492,    0],
        [   0,    0,    0,    0,    1,    6,    0,  218, 4144]])
Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[  39,  206, 2855,  279,  193,  185,    0,  364,    0],
        [   0, 4246,    0,    0,    0,  132,    0,   90,    0],
        [  30,  378, 4811,  250,  363,  571,    0,  774,    0],
        [  60,  201, 2975,  339,  150,  153,    0,  400,    0],
        [  18,  266, 2731,  116,  182,  483,    0,  515,   

Metric Validation/Accuracy improved by 0.081 >= min_delta = 0.0. New best score: 0.453


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[ 120,  206, 4108,  810,  215,  236,    3,  439,    0],
        [   0, 6418,    0,    0,    0,  135,    0,   90,    0],
        [ 109,  384, 7295,  756,  418,  813,    3,  893,    0],
        [ 128,  201, 4268,  962,  164,  202,    0,  446,    0],
        [  53,  266, 4095,  284,  283,  788,    8,  634,    0],
        [   1,  282, 2347,   37,  145, 2339,   12, 1260,    0],
        [  61,  222, 4184,  464,  209,  610,    2,  617,    0],
        [   4,  249, 1718,   58,   75, 1049,    3, 3341,    0],
        [   0,    0,    0,    0,    1,    6,    0,  218, 6288]])
Epoch end: Train, epoch number: 2
TrainEpoch/CM
 tensor([[ 120,  206, 4108,  810,  215,  236,    3,  439,    0],
        [   0, 6418,    0,    0,    0,  135,    0,   90,    0],
        [ 109,  384, 7295,  756,  418,  813,    3,  893,    0],
        [ 128,  201, 4268,  962,  164,  202,    0,  446,    0],
        [  53,  266, 4095,  284,  283,  788,    8,  634,   

Metric Validation/Accuracy improved by 0.069 >= min_delta = 0.0. New best score: 0.522


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[ 204,  206, 5454, 1239,  266,  261,   61,  462,    0],
        [   0, 8591,    0,    0,    0,  137,    0,   90,    0],
        [ 199,  384, 9954, 1081,  631,  928,   69,  919,    0],
        [ 208,  201, 5703, 1387,  227,  226,   45,  467,    0],
        [  74,  266, 5124,  366,  869, 1105,   35,  672,    0],
        [   1,  285, 2526,   40,  319, 3874,   25, 1458,    0],
        [ 105,  222, 5621,  645,  365,  781,   46,  672,    0],
        [   7,  249, 1734,   70,   77, 1199,   10, 5281,    0],
        [   0,    0,    0,    0,    1,    6,    0,  218, 8432]])
Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[ 204,  206, 5454, 1239,  266,  261,   61,  462,    0],
        [   0, 8591,    0,    0,    0,  137,    0,   90,    0],
        [ 199,  384, 9954, 1081,  631,  928,   69,  919,    0],
        [ 208,  201, 5703, 1387,  227,  226,   45,  467,    0],
        [  74,  266, 5124,  366,  869, 1105,   35,  672,   

Metric Validation/Accuracy improved by 0.029 >= min_delta = 0.0. New best score: 0.550


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[  499,   206,  6784,  1441,   341,   282,   140,   476,     0],
        [    0, 10766,     0,     0,     0,   137,     0,    90,     0],
        [  344,   384, 12693,  1250,   926,   977,   153,   932,     0],
        [  385,   201,  7169,  1603,   338,   246,   140,   475,     0],
        [  102,   266,  5849,   412,  1812,  1368,   108,   694,     0],
        [    1,   287,  2571,    40,   479,  5611,    67,  1577,     0],
        [  206,   222,  6952,   744,   621,   917,   175,   708,     0],
        [   10,   249,  1737,    73,    78,  1288,    24,  7298,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 10576]])
Epoch end: Train, epoch number: 4


Metric Validation/Accuracy improved by 0.056 >= min_delta = 0.0. New best score: 0.606


TrainEpoch/CM
 tensor([[  499,   206,  6784,  1441,   341,   282,   140,   476,     0],
        [    0, 10766,     0,     0,     0,   137,     0,    90,     0],
        [  344,   384, 12693,  1250,   926,   977,   153,   932,     0],
        [  385,   201,  7169,  1603,   338,   246,   140,   475,     0],
        [  102,   266,  5849,   412,  1812,  1368,   108,   694,     0],
        [    1,   287,  2571,    40,   479,  5611,    67,  1577,     0],
        [  206,   222,  6952,   744,   621,   917,   175,   708,     0],
        [   10,   249,  1737,    73,    78,  1288,    24,  7298,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 10576]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[ 1251,   206,  7784,  1545,   412,   289,   211,   487,     0],
        [    0, 12939,     0,     0,     0,   139,     0,    90,     0],
        [  703,   384, 15440,  1311,  1153,  1002,   227,   933,     0],
        [  806,   201,  8384,  1773,   505,   260,   242,   479,     0],
        [  171,   266,  6421,   473,  2932,  1563,   173,   712,     0],
        [    1,   287,  2584,    45,   627,  7449,    91,  1654,     0],
        [  428,   222,  8228,   800,   871,  1024,   321,   739,     0],
        [   21,   249,  1737,    75,    83,  1337,    39,  9346,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 12720]])
Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[ 1251,   206,  7784,  1545,   412,   289,   211,   487,     0],
        [    0, 12939,     0,     0,     0,   139,     0,    90,     0],
        [  703,   384, 15440,  1311,  1153,  1002,   227,   933,     0],
        [  806,

Metric Validation/Accuracy improved by 0.053 >= min_delta = 0.0. New best score: 0.658


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[ 2212,   206,  8508,  1687,   483,   295,   317,   493,     0],
        [    0, 15112,     0,     0,     0,   141,     0,    90,     0],
        [ 1004,   384, 18173,  1376,  1400,  1017,   358,   935,     0],
        [ 1232,   201,  9378,  2051,   742,   285,   370,   484,     0],
        [  250,   266,  6876,   557,  4127,  1731,   276,   728,     0],
        [    1,   288,  2592,    49,   752,  9337,   121,  1703,     0],
        [  643,   222,  9395,   882,  1115,  1132,   576,   756,     0],
        [   37,   249,  1737,    78,    88,  1368,    49, 11411,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 14864]])
Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[ 2212,   206,  8508,  1687,   483,   295,   317,   493,     0],
        [    0, 15112,     0,     0,     0,   141,     0,    90,     0],
        [ 1004,   384, 18173,  1376,  1400,  1017,   358,   935,     0],
        [ 1232,

Metric Validation/Accuracy improved by 0.028 >= min_delta = 0.0. New best score: 0.687


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[ 3367,   206,  9025,  1909,   526,   297,   389,   498,     0],
        [    0, 17282,     0,     0,     0,   143,     0,    93,     0],
        [ 1350,   384, 20818,  1509,  1601,  1024,   520,   935,     0],
        [ 1630,   201, 10239,  2507,   969,   297,   504,   489,     0],
        [  308,   266,  7305,   688,  5356,  1872,   380,   736,     0],
        [    1,   288,  2598,    52,   875, 11265,   145,  1724,     0],
        [  823,   222, 10524,  1038,  1340,  1225,   865,   772,     0],
        [   53,   249,  1737,    83,    93,  1385,    56, 13491,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 17008]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[ 3367,   206,  9025,  1909,   526,   297,   389,   498,     0],
        [    0, 17282,     0,     0,     0,   143,     0,    93,     0],
        [ 1350,   384, 20818,  1509,  1601,  1024,   520,   935,     0],
        [ 1630,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[ 4617,   206,  9431,  2128,   587,   299,   462,   501,     2],
        [    0, 19454,     0,     0,     0,   143,     0,    96,     0],
        [ 1649,   384, 23385,  1653,  1811,  1032,   786,   935,     0],
        [ 1965,   201, 10999,  3033,  1273,   309,   656,   493,     0],
        [  355,   266,  7632,   840,  6662,  1998,   512,   746,     0],
        [    1,   288,  2598,    56,   980, 13228,   166,  1736,     0],
        [  953,   222, 11513,  1232,  1575,  1332,  1285,   785,     0],
        [   67,   249,  1737,    84,   101,  1396,    60, 15583,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 19152]])
Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[ 4617,   206,  9431,  2128,   587,   299,   462,   501,     2],
        [    0, 19454,     0,     0,     0,   143,     0,    96,     0],
        [ 1649,   384, 23385,  1653,  1811,  1032,   786,   935,     0],
        [ 1965,

Metric Validation/Accuracy improved by 0.044 >= min_delta = 0.0. New best score: 0.730


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[ 6039,   206,  9712,  2360,   624,   299,   502,   504,     3],
        [    0, 21625,     0,     0,     0,   144,     0,    99,     0],
        [ 1925,   384, 25915,  1864,  2017,  1035,  1054,   935,     0],
        [ 2254,   201, 11719,  3729,  1504,   318,   801,   496,     0],
        [  401,   266,  7955,   998,  7985,  2086,   663,   757,     0],
        [    1,   288,  2599,    60,  1067, 15208,   190,  1745,     0],
        [ 1077,   222, 12445,  1489,  1789,  1426,  1740,   797,     0],
        [   85,   249,  1737,    84,   107,  1400,    60, 17685,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 21296]])
Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[ 6039,   206,  9712,  2360,   624,   299,   502,   504,     3],
        [    0, 21625,     0,     0,     0,   144,     0,    99,     0],
        [ 1925,   384, 25915,  1864,  2017,  1035,  1054,   935,     0],
        [ 2254

Metric Validation/Accuracy improved by 0.025 >= min_delta = 0.0. New best score: 0.755


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[ 7580,   206,  9933,  2534,   668,   299,   532,   508,     5],
        [    0, 23797,     0,     0,     0,   145,     0,   101,     0],
        [ 2117,   384, 28598,  2038,  2224,  1038,  1289,   935,     0],
        [ 2470,   201, 12471,  4447,  1752,   325,   951,   498,     0],
        [  437,   266,  8268,  1151,  9365,  2166,   790,   768,     0],
        [    1,   288,  2600,    60,  1150, 17204,   211,  1749,     0],
        [ 1161,   222, 13429,  1719,  1994,  1528,  2212,   808,     0],
        [   97,   249,  1737,    84,   112,  1409,    61, 19788,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 23440]])
Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[ 7580,   206,  9933,  2534,   668,   299,   532,   508,     5],
        [    0, 23797,     0,     0,     0,   145,     0,   101,     0],
        [ 2117,   384, 28598,  2038,  2224,  1038,  1289,   935,     0],
        [ 247

Metric Validation/Accuracy improved by 0.004 >= min_delta = 0.0. New best score: 0.758


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[ 9224,   206, 10084,  2707,   693,   299,   549,   511,     8],
        [    0, 25971,     0,     0,     0,   146,     0,   101,     0],
        [ 2284,   384, 31198,  2310,  2413,  1043,  1550,   935,     0],
        [ 2650,   201, 13155,  5366,  1932,   333,  1073,   498,     0],
        [  465,   266,  8561,  1348, 10751,  2228,   912,   780,     0],
        [    1,   288,  2601,    63,  1214, 19208,   234,  1759,     0],
        [ 1230,   222, 14368,  2002,  2171,  1619,  2730,   819,     0],
        [  111,   249,  1737,    84,   116,  1414,    63, 21893,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 25584]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[ 9224,   206, 10084,  2707,   693,   299,   549,   511,     8],
        [    0, 25971,     0,     0,     0,   146,     0,   101,     0],
        [ 2284,   384, 31198,  2310,  2413,  1043,  1550,   935,     0],
        [ 265

Metric Validation/Accuracy improved by 0.018 >= min_delta = 0.0. New best score: 0.776


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[10898,   207, 10245,  2854,   710,   299,   561,   513,    10],
        [    0, 28145,     0,     0,     0,   146,     0,   102,     0],
        [ 2391,   384, 33974,  2550,  2566,  1045,  1766,   935,     0],
        [ 2780,   201, 13926,  6270,  2097,   338,  1191,   498,     0],
        [  494,   266,  8889,  1547, 12127,  2275,  1019,   794,     0],
        [    1,   289,  2603,    67,  1263, 21220,   265,  1765,     0],
        [ 1269,   222, 15415,  2282,  2346,  1701,  3186,   828,     0],
        [  123,   249,  1737,    84,   122,  1421,    66, 23995,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 27728]])
Epoch end: Train, epoch number: 12
TrainEpoch/CM
 tensor([[10898,   207, 10245,  2854,   710,   299,   561,   513,    10],
        [    0, 28145,     0,     0,     0,   146,     0,   102,     0],
        [ 2391,   384, 33974,  2550,  2566,  1045,  1766,   935,     0],
        [ 278

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[12609,   207, 10365,  3003,   733,   299,   570,   514,    13],
        [    0, 30320,     0,     0,     0,   146,     0,   102,     0],
        [ 2481,   384, 36778,  2786,  2702,  1047,  1992,   935,     0],
        [ 2902,   201, 14668,  7219,  2257,   340,  1309,   498,     0],
        [  513,   266,  9230,  1745, 13507,  2320,  1122,   808,     0],
        [    1,   289,  2606,    71,  1315, 23228,   293,  1775,     0],
        [ 1302,   222, 16477,  2567,  2498,  1776,  3654,   841,     0],
        [  136,   249,  1737,    87,   128,  1433,    66, 26091,     0],
        [    0,     0,     0,     0,     1,     6,     0,   218, 29872]])
Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[12609,   207, 10365,  3003,   733,   299,   570,   514,    13],
        [    0, 30320,     0,     0,     0,   146,     0,   102,     0],
        [ 2481,   384, 36778,  2786,  2702,  1047,  1992,   935,     0],
        [ 290

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[14298,   207, 10481,  3172,   759,   299,   582,   517,    14],
        [    0, 32495,     0,     0,     0,   146,     0,   102,     0],
        [ 2570,   384, 39598,  3016,  2820,  1057,  2219,   935,     0],
        [ 3013,   201, 15355,  8220,  2402,   348,  1450,   498,     0],
        [  538,   266,  9517,  1963, 14899,  2370,  1237,   821,     0],
        [    1,   289,  2607,    76,  1366, 25234,   329,  1781,     0],
        [ 1342,   222, 17489,  2868,  2642,  1858,  4150,   854,     0],
        [  146,   249,  1737,    88,   131,  1450,    68, 28188,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 32014]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[14298,   207, 10481,  3172,   759,   299,   582,   517,    14],
        [    0, 32495,     0,     0,     0,   146,     0,   102,     0],
        [ 2570,   384, 39598,  3016,  2820,  1057,  2219,   935,     0],
        [ 301

Metric Validation/Accuracy improved by 0.002 >= min_delta = 0.0. New best score: 0.778


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 16
ValidationEpoch/CM
 tensor([[16037,   207, 10579,  3307,   789,   299,   593,   519,    15],
        [    0, 34669,     0,     0,     0,   146,     0,   103,     0],
        [ 2670,   384, 42318,  3275,  2944,  1061,  2506,   935,     0],
        [ 3151,   201, 16011,  9234,  2550,   349,  1585,   499,     0],
        [  565,   266,  9781,  2185, 16334,  2405,  1347,   828,     0],
        [    1,   290,  2612,    82,  1411, 27235,   366,  1791,     0],
        [ 1375,   222, 18441,  3187,  2798,  1947,  4678,   865,     0],
        [  154,   249,  1737,    90,   135,  1464,    71, 30287,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 34158]])


Metric Validation/Accuracy improved by 0.019 >= min_delta = 0.0. New best score: 0.797


Epoch end: Train, epoch number: 15
TrainEpoch/CM
 tensor([[16037,   207, 10579,  3307,   789,   299,   593,   519,    15],
        [    0, 34669,     0,     0,     0,   146,     0,   103,     0],
        [ 2670,   384, 42318,  3275,  2944,  1061,  2506,   935,     0],
        [ 3151,   201, 16011,  9234,  2550,   349,  1585,   499,     0],
        [  565,   266,  9781,  2185, 16334,  2405,  1347,   828,     0],
        [    1,   290,  2612,    82,  1411, 27235,   366,  1791,     0],
        [ 1375,   222, 18441,  3187,  2798,  1947,  4678,   865,     0],
        [  154,   249,  1737,    90,   135,  1464,    71, 30287,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 34158]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 17
ValidationEpoch/CM
 tensor([[17799,   207, 10664,  3442,   813,   299,   601,   521,    15],
        [    0, 36844,     0,     0,     0,   146,     0,   103,     0],
        [ 2749,   384, 44946,  3582,  3077,  1065,  2849,   935,     0],
        [ 3233,   201, 16630, 10341,  2704,   352,  1713,   499,     0],
        [  583,   266, 10042,  2402, 17790,  2445,  1446,   837,     0],
        [    1,   290,  2615,    90,  1445, 29260,   393,  1799,     0],
        [ 1402,   222, 19341,  3497,  2957,  2034,  5275,   873,     0],
        [  162,   249,  1737,    90,   137,  1478,    77, 32387,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 36302]])
Epoch end: Train, epoch number: 16


Metric Validation/Accuracy improved by 0.003 >= min_delta = 0.0. New best score: 0.800


TrainEpoch/CM
 tensor([[17799,   207, 10664,  3442,   813,   299,   601,   521,    15],
        [    0, 36844,     0,     0,     0,   146,     0,   103,     0],
        [ 2749,   384, 44946,  3582,  3077,  1065,  2849,   935,     0],
        [ 3233,   201, 16630, 10341,  2704,   352,  1713,   499,     0],
        [  583,   266, 10042,  2402, 17790,  2445,  1446,   837,     0],
        [    1,   290,  2615,    90,  1445, 29260,   393,  1799,     0],
        [ 1402,   222, 19341,  3497,  2957,  2034,  5275,   873,     0],
        [  162,   249,  1737,    90,   137,  1478,    77, 32387,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 36302]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 18
ValidationEpoch/CM
 tensor([[19550,   207, 10758,  3583,   833,   299,   609,   523,    15],
        [    0, 39019,     0,     0,     0,   146,     0,   103,     0],
        [ 2816,   384, 47714,  3820,  3197,  1067,  3148,   935,     0],
        [ 3312,   201, 17259, 11439,  2854,   352,  1850,   499,     0],
        [  602,   266, 10296,  2619, 19245,  2481,  1556,   846,     0],
        [    1,   290,  2617,    96,  1473, 31283,   431,  1807,     0],
        [ 1420,   222, 20278,  3784,  3114,  2104,  5885,   882,     0],
        [  170,   249,  1737,    91,   140,  1490,    80, 34490,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 38446]])
Epoch end: Train, epoch number: 17
TrainEpoch/CM
 tensor([[19550,   207, 10758,  3583,   833,   299,   609,   523,    15],
        [    0, 39019,     0,     0,     0,   146,     0,   103,     0],
        [ 2816,   384, 47714,  3820,  3197,  1067,  3148,   935,     0],
        [ 331

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 19
ValidationEpoch/CM
 tensor([[21314,   207, 10834,  3722,   865,   299,   613,   524,    15],
        [    0, 41193,     0,     0,     0,   146,     0,   104,     0],
        [ 2875,   384, 50397,  4057,  3363,  1070,  3494,   935,     0],
        [ 3403,   201, 17874, 12474,  3055,   355,  1998,   499,     0],
        [  621,   266, 10540,  2832, 20734,  2503,  1659,   856,     0],
        [    1,   290,  2620,   100,  1511, 33301,   465,  1815,     0],
        [ 1448,   222, 21195,  4070,  3313,  2176,  6461,   892,     0],
        [  178,   249,  1737,    91,   145,  1506,    84, 36587,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 40590]])
Epoch end: Train, epoch number: 18
TrainEpoch/CM
 tensor([[21314,   207, 10834,  3722,   865,   299,   613,   524,    15],
        [    0, 41193,     0,     0,     0,   146,     0,   104,     0],
        [ 2875,   384, 50397,  4057,  3363,  1070,  3494,   935,     0],
        [ 340

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 20
ValidationEpoch/CM
 tensor([[23086,   207, 10904,  3862,   894,   299,   618,   524,    15],
        [    0, 43368,     0,     0,     0,   146,     0,   104,     0],
        [ 2926,   384, 53182,  4304,  3477,  1074,  3787,   935,     0],
        [ 3478,   201, 18481, 13597,  3224,   356,  2116,   499,     0],
        [  640,   266, 10778,  3045, 22229,  2530,  1760,   863,     0],
        [    1,   290,  2620,   104,  1532, 35339,   502,  1820,     0],
        [ 1471,   222, 22096,  4356,  3461,  2256,  7102,   901,     0],
        [  184,   249,  1737,    91,   147,  1521,    90, 38688,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 42734]])


Metric Validation/Accuracy improved by 0.004 >= min_delta = 0.0. New best score: 0.804


Epoch end: Train, epoch number: 19
TrainEpoch/CM
 tensor([[23086,   207, 10904,  3862,   894,   299,   618,   524,    15],
        [    0, 43368,     0,     0,     0,   146,     0,   104,     0],
        [ 2926,   384, 53182,  4304,  3477,  1074,  3787,   935,     0],
        [ 3478,   201, 18481, 13597,  3224,   356,  2116,   499,     0],
        [  640,   266, 10778,  3045, 22229,  2530,  1760,   863,     0],
        [    1,   290,  2620,   104,  1532, 35339,   502,  1820,     0],
        [ 1471,   222, 22096,  4356,  3461,  2256,  7102,   901,     0],
        [  184,   249,  1737,    91,   147,  1521,    90, 38688,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 42734]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 21
ValidationEpoch/CM
 tensor([[24889,   207, 10971,  3980,   916,   299,   623,   525,    15],
        [    0, 45543,     0,     0,     0,   146,     0,   104,     0],
        [ 3023,   384, 55970,  4531,  3593,  1077,  4050,   935,     0],
        [ 3609,   201, 19075, 14692,  3377,   357,  2235,   499,     0],
        [  668,   266, 11008,  3266, 23735,  2548,  1851,   869,     0],
        [    1,   290,  2621,   115,  1556, 37342,   557,  1831,     0],
        [ 1499,   222, 23084,  4632,  3606,  2324,  7678,   908,     0],
        [  190,   249,  1737,    91,   150,  1530,    97, 40793,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 44878]])
Epoch end: Train, epoch number: 20
TrainEpoch/CM
 tensor([[24889,   207, 10971,  3980,   916,   299,   623,   525,    15],
        [    0, 45543,     0,     0,     0,   146,     0,   104,     0],
        [ 3023,   384, 55970,  4531,  3593,  1077,  4050,   935,     0],
        [ 360

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 22
ValidationEpoch/CM
 tensor([[26532,   209, 11078,  4189,   955,   299,   638,   526,    15],
        [    0, 47718,     0,     0,     0,   146,     0,   104,     0],
        [ 3108,   384, 58622,  4756,  3717,  1091,  4444,   935,     0],
        [ 3749,   201, 19638, 15760,  3546,   363,  2381,   500,     0],
        [  696,   266, 11226,  3463, 25223,  2607,  1955,   875,     0],
        [    1,   290,  2626,   119,  1584, 39362,   595,  1841,     0],
        [ 1533,   222, 23970,  4895,  3766,  2448,  8291,   916,     0],
        [  196,   249,  1737,    91,   151,  1543,   105, 42895,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 47022]])
Epoch end: Train, epoch number: 21
TrainEpoch/CM
 tensor([[26532,   209, 11078,  4189,   955,   299,   638,   526,    15],
        [    0, 47718,     0,     0,     0,   146,     0,   104,     0],
        [ 3108,   384, 58622,  4756,  3717,  1091,  4444,   935,     0],
        [ 374

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 23
ValidationEpoch/CM
 tensor([[28275,   211, 11160,  4338,   985,   299,   647,   527,    15],
        [    0, 49892,     0,     0,     0,   146,     0,   105,     0],
        [ 3201,   384, 61437,  4975,  3830,  1094,  4695,   935,     0],
        [ 3860,   201, 20265, 16854,  3700,   369,  2480,   502,     0],
        [  729,   266, 11474,  3700, 26694,  2634,  2033,   881,     0],
        [    1,   292,  2631,   130,  1601, 41383,   639,  1846,     0],
        [ 1568,   222, 24990,  5175,  3915,  2519,  8818,   922,     0],
        [  200,   249,  1737,    91,   151,  1552,   113, 45004,     0],
        [    2,     0,     0,     0,     1,     6,     0,   218, 49166]])
Epoch end: Train, epoch number: 22
TrainEpoch/CM
 tensor([[28275,   211, 11160,  4338,   985,   299,   647,   527,    15],
        [    0, 49892,     0,     0,     0,   146,     0,   105,     0],
        [ 3201,   384, 61437,  4975,  3830,  1094,  4695,   935,     0],
        [ 386

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 24
ValidationEpoch/CM
 tensor([[30074,   212, 11233,  4454,  1007,   299,   650,   527,    17],
        [    0, 52067,     0,     0,     0,   146,     0,   105,     0],
        [ 3294,   384, 64143,  5284,  3953,  1097,  4955,   935,     0],
        [ 3966,   201, 20818, 18041,  3848,   372,  2576,   502,     0],
        [  754,   266, 11677,  3973, 28184,  2645,  2126,   886,     0],
        [    1,   293,  2636,   140,  1622, 43386,   695,  1855,     0],
        [ 1601,   222, 25901,  5527,  4060,  2590,  9389,   927,     0],
        [  208,   249,  1737,    92,   152,  1559,   119, 47111,     0],
        [    3,     0,     0,     0,     1,     6,     0,   218, 51309]])
Epoch end: Train, epoch number: 23
TrainEpoch/CM
 tensor([[30074,   212, 11233,  4454,  1007,   299,   650,   527,    17],
        [    0, 52067,     0,     0,     0,   146,     0,   105,     0],
        [ 3294,   384, 64143,  5284,  3953,  1097,  4955,   935,     0],
        [ 396

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 25
ValidationEpoch/CM
 tensor([[31869,   212, 11303,  4569,  1029,   299,   663,   527,    18],
        [    0, 54242,     0,     0,     0,   146,     0,   105,     0],
        [ 3370,   384, 66891,  5505,  4064,  1099,  5291,   935,     0],
        [ 4074,   201, 21398, 19150,  4012,   373,  2707,   502,     0],
        [  780,   266, 11896,  4216, 29668,  2659,  2237,   889,     0],
        [    1,   293,  2637,   145,  1638, 45409,   749,  1861,     0],
        [ 1625,   222, 26835,  5821,  4206,  2653, 10013,   930,     0],
        [  213,   249,  1737,    92,   154,  1567,   125, 49220,     0],
        [    3,     0,     0,     0,     1,     6,     0,   218, 53453]])
Epoch end: Train, epoch number: 24
TrainEpoch/CM
 tensor([[31869,   212, 11303,  4569,  1029,   299,   663,   527,    18],
        [    0, 54242,     0,     0,     0,   146,     0,   105,     0],
        [ 3370,   384, 66891,  5505,  4064,  1099,  5291,   935,     0],
        [ 407

Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 0.804. Signaling Trainer to stop.


In [20]:
model.eval()

MalwaresModelMLP(
  (train_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Train/
  )
  (val_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Validation/
  )
  (test_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Test/
  )
  (cm): MulticlassConfusionMatrix()
  (criterion): CrossEntropyLoss()
  (l1): Linear(in_features=33, out_features=30, bias=True)
  (l2): Linear(in_features=30, out_features=30, bias=True)
  (l3): Linear(in_features=30, out_features=9, bias=True)
)

In [21]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelMLP.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/lightning_logs/version_8/checkpoints/epoch=19-step=660.ckpt
tensor(0.8042, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[340,   0,  13,  45,   6,   0,   2,   0,   0],
        [  0, 448,   0,   0,   0,   0,   0,   0,   0],
        [  7,   0, 572,  57,  21,   1,  76,   0,   0],
        [  4,   0, 101, 225,  28,   0,  19,   0,   0],
        [  1,   0,  35,  61, 289,   9,  27,   1,   0],
        [  0,   0,   0,   2,   2, 427,   5,   0,   0],
        [  3,   0, 145,  58,  18,  19, 151,   2,   0],
        [  1,   0,   0,   0,   0,   3,   1, 419,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 425]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.8042055368423462
      Test/F1Score          0.8072361946105957
        Test/Loss           0.5107317566871643
     Test/Precision         0.

[{'Test/Loss': 0.5107317566871643,
  'Test/Accuracy': 0.8042055368423462,
  'Test/Precision': 0.8186952471733093,
  'Test/Recall': 0.8042055368423462,
  'Test/F1Score': 0.8072361946105957,
  'TestEpoch/Accuracy': 0.8050711750984192,
  'TestEpoch/Precision': 0.8191437125205994,
  'TestEpoch/Recall': 0.8050711750984192,
  'TestEpoch/F1Score': 0.8086774349212646}]

In [22]:
x,t = next(iter(train_dataloader))

z = model(x)

torch.argmax(z, dim=0)

tensor([435,  10,  55, 323, 424, 132, 296, 420,  30])