# Idea
Do some training

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import pickle

In [2]:
import sys
repo_base_path = Path("./../").resolve()
assert str(repo_base_path).endswith("csg_is"), f"{repo_base_path} is not a valid path to the CSG_IS repository" 

sys.path.append(str(repo_base_path))

# from py_dataset import get_all_files_df
# from py_dataset import read_in_files
from py_dataset import feature_plotting
# from py_dataset import feature_selection
# from py_dataset import net_feature_engineering
# from py_dataset import entropy_feature_engineering
# from py_dataset.classes import DataSource
from py_dataset import sys_func



In [3]:
df = pd.read_csv('all_df.csv')
df.set_index("timestamp", inplace=True)

In [4]:
df["label"].unique()

array(['1_normal', nan, '2_ransomware', '3_thetick', '4_bashlite',
       '5_httpbackdoor', '6_beurk', '7_backdoor', '8_bdvl', '9_xmrig'],
      dtype=object)

### Preprocessings
- remove Null values
- drop timestamp
- labelEncode
- normalize

In [5]:
print(df.shape)
old_df = df.copy()
df.dropna(axis=0, how='any', inplace=True)

print(df.shape)

(43248, 306)
(25770, 306)


In [6]:
df.reset_index(inplace=True, drop=True)

In [7]:
label_encoder = sys_func.create_label_encoder_for_labels()
df['label'] = label_encoder.transform(df['label'])

In [8]:
df = feature_plotting.test_transform_all_to_numeric_columns(df)

In [9]:
cols_to_exclude_from_scaling = ["label"]
vectors = feature_plotting.minmax_scale_features(df,remove_outliers_iqr_all_columns=False,
                                                        cols_to_exclude_from_scaling=cols_to_exclude_from_scaling)
# print(vectors.shape)
# print(" with dropped null: ", vectors.dropna(axis=0, how='any', inplace=False).shape)

In [10]:
df["label"].unique(), vectors["label"].unique()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

### Setup

In [11]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomeDataset(Dataset):
    def __init__(self, some_df:pd.DataFrame):
        
        self.x = torch.tensor(some_df.drop(columns=["label"], inplace=False).values, dtype=torch.float32)
        self.labels = torch.tensor(some_df["label"].values, dtype=torch.uint8)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        # if torch.is_tensor(idx):
        #     idx = idx.tolist()
        # print(self.x[idx], self.labels[idx])
        return self.x[idx], self.labels[idx]

In [17]:
from mlp import MalwaresModelMLP
from torch.utils.data import DataLoader
import lightning
from sklearn.model_selection import train_test_split
from lightning import loggers as pl_loggers
from lightning.pytorch.callbacks.early_stopping import EarlyStopping
from lightning.pytorch.callbacks.model_checkpoint import ModelCheckpoint

# tensorboard = pl_loggers.TensorBoardLogger('./')

# split into train and val
train, val = train_test_split(vectors, test_size=0.2)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True) #logger=None, 


model = MalwaresModelMLP(input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [18]:
trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 9.2 K 
6 | l2            | Linear                    | 930   
7 | l3            | Linear                    | 279   
------------------------------------------------------------
10.4 K    Trainable params
0         Non-trainable params
10.4 K    Total params
0.042     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 101],
        [  0,   0,   0,   0,   0,   0,   1,   0, 117],
        [  0,   0,   0,   0,   0,   0,   0,   0, 124],
        [  0,   0,   0,   0,   0,   0,   0,   0, 105],
        [  0,   0,   0,   0,   0,   0,   0,   0,  98],
        [  0,   0,   0,   0,   0,   0,   0,   0, 113],
        [  0,   0,   0,   0,   0,   0,   0,   0,  94],
        [  0,   0,   0,   0,   0,   0,   2,   0, 119],
        [  0,   0,   0,   0,   0,   0,   0,   0, 126]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (42) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[ 530,  140,  454,  291,  850,    1,  226,    0,  159],
        [   0, 3211,    0,    0,    0,    0,    2,    0,  185],
        [ 107,  213, 1757,   94,  109,  191,  664,    0,  169],
        [ 522,  155,  504,  310,  888,    2,  214,    0,  160],
        [ 382,  133,  512,  232, 1191,   17,  195,    0,  151],
        [   0,  174,  235,    0,    0, 2344,    5,    0,  175],
        [ 214,  166, 1067,  152,  262,   93,  646,    0,  144],
        [   0,  137,    0,    0,    0,    0,    3, 2467,  159],
        [   0,  122,   13,    0,    0,    0,    0,    0, 3271]])


Metric Validation/Accuracy improved. New best score: 0.661


Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[ 530,  140,  454,  291,  850,    1,  226,    0,  159],
        [   0, 3211,    0,    0,    0,    0,    2,    0,  185],
        [ 107,  213, 1757,   94,  109,  191,  664,    0,  169],
        [ 522,  155,  504,  310,  888,    2,  214,    0,  160],
        [ 382,  133,  512,  232, 1191,   17,  195,    0,  151],
        [   0,  174,  235,    0,    0, 2344,    5,    0,  175],
        [ 214,  166, 1067,  152,  262,   93,  646,    0,  144],
        [   0,  137,    0,    0,    0,    0,    3, 2467,  159],
        [   0,  122,   13,    0,    0,    0,    0,    0, 3271]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[1911,  140,  469,  876, 1221,    1,  424,    0,  159],
        [   0, 6491,    0,    0,    0,    0,    2,    0,  185],
        [ 159,  213, 4087,  137,  113,  221, 1385,    0,  169],
        [1596,  155,  547, 1149, 1287,    2,  504,    0,  165],
        [ 653,  133,  533,  480, 3268,   29,  281,    0,  151],
        [   0,  179,  238,    0,    0, 5156,    5,    0,  175],
        [ 485,  166, 2044,  473,  323,  110, 1649,    0,  144],
        [   0,  137,    0,    0,    0,    0,    3, 5112,  159],
        [   0,  122,   13,    0,    0,    0,    0,    0, 6551]])
Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[1911,  140,  469,  876, 1221,    1,  424,    0,  159],
        [   0, 6491,    0,    0,    0,    0,    2,    0,  185],
        [ 159,  213, 4087,  137,  113,  221, 1385,    0,  169],
        [1596,  155,  547, 1149, 1287,    2,  504,    0,  165],
        [ 653,  133,  533,  480, 3268,   29,  281,    0,  1

Metric Validation/Accuracy improved by 0.131 >= min_delta = 0.0. New best score: 0.792


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[3492,  140,  469, 1650, 1294,    1,  546,    0,  159],
        [   0, 9771,    0,    0,    0,    0,    2,    0,  185],
        [ 181,  213, 6572,  184,  115,  240, 1990,    0,  169],
        [2728,  155,  558, 2364, 1349,    2,  734,    0,  165],
        [ 745,  133,  539,  572, 5770,   29,  304,    0,  151],
        [   0,  179,  245,    0,    0, 7969,    5,    0,  175],
        [ 659,  166, 3014,  916,  338,  116, 2691,    0,  144],
        [   0,  137,    0,    0,    0,    0,    3, 7757,  159],
        [   0,  122,   13,    0,    0,    0,    0,    0, 9831]])
Epoch end: Train, epoch number: 2


Metric Validation/Accuracy improved by 0.028 >= min_delta = 0.0. New best score: 0.820


TrainEpoch/CM
 tensor([[3492,  140,  469, 1650, 1294,    1,  546,    0,  159],
        [   0, 9771,    0,    0,    0,    0,    2,    0,  185],
        [ 181,  213, 6572,  184,  115,  240, 1990,    0,  169],
        [2728,  155,  558, 2364, 1349,    2,  734,    0,  165],
        [ 745,  133,  539,  572, 5770,   29,  304,    0,  151],
        [   0,  179,  245,    0,    0, 7969,    5,    0,  175],
        [ 659,  166, 3014,  916,  338,  116, 2691,    0,  144],
        [   0,  137,    0,    0,    0,    0,    3, 7757,  159],
        [   0,  122,   13,    0,    0,    0,    0,    0, 9831]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[ 5314,   140,   469,  2282,  1297,     1,   639,     0,   159],
        [    0, 13051,     0,     0,     0,     0,     2,     0,   185],
        [  193,   213,  9080,   201,   115,   251,  2622,     0,   169],
        [ 3795,   155,   571,  3743,  1356,     2,   918,     0,   165],
        [  779,   133,   542,   632,  8377,    29,   315,     0,   151],
        [    0,   179,   247,     0,     0, 10787,     5,     0,   175],
        [  764,   166,  3933,  1217,   341,   123,  4006,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 10402,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 13111]])
Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[ 5314,   140,   469,  2282,  1297,     1,   639,     0,   159],
        [    0, 13051,     0,     0,     0,     0,     2,     0,   185],
        [  193,   213,  9080,   201,   115,   251,  2622,     0,   169],
        [ 3795,

Metric Validation/Accuracy improved by 0.023 >= min_delta = 0.0. New best score: 0.843


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[ 7295,   140,   469,  2808,  1303,     1,   676,     0,   159],
        [    0, 16331,     0,     0,     0,     0,     2,     0,   185],
        [  195,   213, 11490,   217,   115,   254,  3371,     0,   169],
        [ 4886,   155,   580,  5171,  1356,     2,  1040,     0,   165],
        [  806,   133,   542,   664, 11024,    29,   324,     0,   151],
        [    0,   179,   247,     0,     0, 13607,     5,     0,   175],
        [  922,   166,  4668,  1477,   343,   125,  5499,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 13047,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 16391]])
Epoch end: Train, epoch number: 4
TrainEpoch/CM
 tensor([[ 7295,   140,   469,  2808,  1303,     1,   676,     0,   159],
        [    0, 16331,     0,     0,     0,     0,     2,     0,   185],
        [  195,   213, 11490,   217,   115,   254,  3371,     0,   169],
        [ 4886,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[ 9054,   140,   469,  3558,  1303,     1,   717,     0,   159],
        [    0, 19611,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 14177,   221,   115,   258,  3855,     0,   169],
        [ 5415,   155,   586,  7172,  1361,     2,  1149,     0,   165],
        [  811,   133,   542,   699, 13693,    29,   330,     0,   151],
        [    0,   179,   247,     0,     0, 16427,     5,     0,   175],
        [  991,   166,  5545,  1726,   344,   131,  6947,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 15692,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 19671]])
Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[ 9054,   140,   469,  3558,  1303,     1,   717,     0,   159],
        [    0, 19611,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 14177,   221,   115,   258,  3855,     0,   169],
        [ 5415,

Metric Validation/Accuracy improved by 0.009 >= min_delta = 0.0. New best score: 0.852


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[11216,   140,   469,  3912,  1307,     1,   747,     0,   159],
        [    0, 22891,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 16698,   228,   115,   261,  4504,     0,   169],
        [ 5838,   155,   589,  9311,  1365,     2,  1230,     0,   165],
        [  821,   133,   542,   725, 16362,    29,   340,     0,   151],
        [    0,   179,   250,     0,     0, 19240,     9,     0,   175],
        [ 1043,   166,  6189,  2037,   346,   136,  8583,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 18337,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 22951]])
Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[11216,   140,   469,  3912,  1307,     1,   747,     0,   159],
        [    0, 22891,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 16698,   228,   115,   261,  4504,     0,   169],
        [ 5838,

Metric Validation/Accuracy improved by 0.058 >= min_delta = 0.0. New best score: 0.910


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[13601,   140,   469,  4041,  1308,     1,   782,     0,   159],
        [    0, 26171,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 19375,   233,   115,   264,  4999,     0,   169],
        [ 6033,   155,   594, 11625,  1365,     2,  1366,     0,   165],
        [  821,   133,   542,   729, 19071,    29,   342,     0,   151],
        [    0,   179,   250,     0,     0, 22060,     9,     0,   175],
        [ 1063,   166,  6732,  2273,   346,   140, 10430,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 20982,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 26231]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[13601,   140,   469,  4041,  1308,     1,   782,     0,   159],
        [    0, 26171,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 19375,   233,   115,   264,  4999,     0,   169],
        [ 6033,

Metric Validation/Accuracy improved by 0.025 >= min_delta = 0.0. New best score: 0.935


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[16067,   140,   469,  4110,  1308,     1,   797,     0,   159],
        [    0, 29451,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 21903,   240,   115,   264,  5644,     0,   169],
        [ 6225,   155,   596, 13999,  1365,     2,  1448,     0,   165],
        [  821,   133,   542,   731, 21784,    29,   342,     0,   151],
        [    0,   179,   251,     0,     0, 24879,     9,     0,   175],
        [ 1088,   166,  7175,  2475,   346,   143, 12407,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 23627,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 29511]])
Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[16067,   140,   469,  4110,  1308,     1,   797,     0,   159],
        [    0, 29451,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 21903,   240,   115,   264,  5644,     0,   169],
        [ 6225,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[18581,   140,   469,  4138,  1308,     1,   805,     0,   159],
        [    0, 32731,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 24656,   240,   115,   264,  6071,     0,   169],
        [ 6275,   155,   601, 16526,  1365,     2,  1516,     0,   165],
        [  821,   133,   542,   732, 24498,    29,   342,     0,   151],
        [    0,   179,   251,     0,     0, 27699,     9,     0,   175],
        [ 1099,   166,  7582,  2669,   347,   147, 14440,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 26272,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 32791]])
Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[18581,   140,   469,  4138,  1308,     1,   805,     0,   159],
        [    0, 32731,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 24656,   240,   115,   264,  6071,     0,   169],
        [ 6275

Metric Validation/Accuracy improved by 0.020 >= min_delta = 0.0. New best score: 0.955


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[21098,   140,   469,  4162,  1308,     1,   814,     0,   159],
        [    0, 36011,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 27448,   245,   115,   264,  6454,     0,   169],
        [ 6322,   155,   606, 19038,  1365,     2,  1602,     0,   165],
        [  821,   133,   542,   733, 27212,    29,   342,     0,   151],
        [    0,   179,   251,     0,     0, 30519,     9,     0,   175],
        [ 1109,   166,  7963,  2873,   347,   153, 16489,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 28917,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 36071]])
Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[21098,   140,   469,  4162,  1308,     1,   814,     0,   159],
        [    0, 36011,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 27448,   245,   115,   264,  6454,     0,   169],
        [ 632

Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.961


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[23547,   140,   469,  4243,  1308,     1,   834,     0,   159],
        [    0, 39291,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 30304,   246,   115,   264,  6777,     0,   169],
        [ 6396,   155,   611, 21546,  1365,     2,  1665,     0,   165],
        [  821,   133,   542,   734, 29926,    29,   342,     0,   151],
        [    0,   179,   251,     0,     0, 33339,     9,     0,   175],
        [ 1121,   166,  8341,  3062,   348,   155, 18557,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 31562,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 39351]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[23547,   140,   469,  4243,  1308,     1,   834,     0,   159],
        [    0, 39291,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 30304,   246,   115,   264,  6777,     0,   169],
        [ 639

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[26062,   140,   469,  4268,  1308,     1,   844,     0,   159],
        [    0, 42571,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 33180,   246,   115,   266,  7079,     0,   169],
        [ 6437,   155,   616, 24075,  1365,     2,  1740,     0,   165],
        [  821,   133,   542,   735, 32635,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 36155,    11,     0,   175],
        [ 1133,   166,  8734,  3233,   349,   161, 20624,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 34207,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 42631]])
Epoch end: Train, epoch number: 12


Metric Validation/Accuracy improved by 0.005 >= min_delta = 0.0. New best score: 0.966


TrainEpoch/CM
 tensor([[26062,   140,   469,  4268,  1308,     1,   844,     0,   159],
        [    0, 42571,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 33180,   246,   115,   266,  7079,     0,   169],
        [ 6437,   155,   616, 24075,  1365,     2,  1740,     0,   165],
        [  821,   133,   542,   735, 32635,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 36155,    11,     0,   175],
        [ 1133,   166,  8734,  3233,   349,   161, 20624,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 34207,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 42631]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[28606,   140,   469,  4274,  1308,     1,   844,     0,   159],
        [    0, 45851,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 36133,   248,   115,   266,  7304,     0,   169],
        [ 6449,   155,   622, 26633,  1365,     2,  1814,     0,   165],
        [  821,   133,   542,   735, 35350,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 38975,    11,     0,   175],
        [ 1136,   166,  8988,  3394,   349,   164, 22853,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 36852,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 45911]])


Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.972


Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[28606,   140,   469,  4274,  1308,     1,   844,     0,   159],
        [    0, 45851,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 36133,   248,   115,   266,  7304,     0,   169],
        [ 6449,   155,   622, 26633,  1365,     2,  1814,     0,   165],
        [  821,   133,   542,   735, 35350,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 38975,    11,     0,   175],
        [ 1136,   166,  8988,  3394,   349,   164, 22853,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 36852,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 45911]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[31150,   140,   469,  4276,  1308,     1,   848,     0,   159],
        [    0, 49131,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 39021,   260,   115,   266,  7584,     0,   169],
        [ 6463,   155,   627, 29147,  1365,     2,  1931,     0,   165],
        [  821,   133,   542,   735, 38065,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 41795,    11,     0,   175],
        [ 1139,   166,  9226,  3604,   349,   168, 25048,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 39497,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 49191]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[31150,   140,   469,  4276,  1308,     1,   848,     0,   159],
        [    0, 49131,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 39021,   260,   115,   266,  7584,     0,   169],
        [ 646

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 16
ValidationEpoch/CM
 tensor([[33695,   140,   469,  4281,  1308,     1,   848,     0,   159],
        [    0, 52411,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 41816,   262,   115,   266,  7967,     0,   169],
        [ 6476,   155,   632, 31720,  1365,     2,  1990,     0,   165],
        [  821,   133,   542,   735, 40780,    29,   347,     0,   151],
        [    0,   179,   253,     0,     0, 44613,    13,     0,   175],
        [ 1143,   166,  9423,  3766,   349,   170, 27333,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 42142,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 52471]])
Epoch end: Train, epoch number: 15
TrainEpoch/CM
 tensor([[33695,   140,   469,  4281,  1308,     1,   848,     0,   159],
        [    0, 52411,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 41816,   262,   115,   266,  7967,     0,   169],
        [ 647

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 17
ValidationEpoch/CM
 tensor([[36217,   140,   469,  4307,  1308,     1,   850,     0,   159],
        [    0, 55691,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 44639,   262,   115,   267,  8323,     0,   169],
        [ 6511,   155,   634, 34274,  1365,     2,  2049,     0,   165],
        [  821,   133,   542,   735, 43495,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 47431,    13,     0,   175],
        [ 1148,   166,  9699,  3930,   349,   176, 29532,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 44787,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 55751]])
Epoch end: Train, epoch number: 16
TrainEpoch/CM
 tensor([[36217,   140,   469,  4307,  1308,     1,   850,     0,   159],
        [    0, 55691,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 44639,   262,   115,   267,  8323,     0,   169],
        [ 651

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 18
ValidationEpoch/CM
 tensor([[38762,   140,   469,  4312,  1308,     1,   850,     0,   159],
        [    0, 58971,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 47644,   262,   115,   267,  8498,     0,   169],
        [ 6519,   155,   640, 36836,  1365,     2,  2123,     0,   165],
        [  821,   133,   542,   736, 46209,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 50251,    13,     0,   175],
        [ 1148,   166, 10002,  4075,   349,   179, 31731,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 47432,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 59031]])
Epoch end: Train, epoch number: 17
TrainEpoch/CM
 tensor([[38762,   140,   469,  4312,  1308,     1,   850,     0,   159],
        [    0, 58971,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 47644,   262,   115,   267,  8498,     0,   169],
        [ 651

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 19
ValidationEpoch/CM
 tensor([[41312,   140,   469,  4312,  1308,     1,   850,     0,   159],
        [    0, 62251,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 50698,   262,   115,   267,  8624,     0,   169],
        [ 6519,   155,   645, 39442,  1365,     2,  2162,     0,   165],
        [  821,   133,   542,   736, 48924,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 53071,    13,     0,   175],
        [ 1148,   166, 10182,  4204,   349,   179, 34072,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 50077,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 62311]])
Epoch end: Train, epoch number: 18
TrainEpoch/CM
 tensor([[41312,   140,   469,  4312,  1308,     1,   850,     0,   159],
        [    0, 62251,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 50698,   262,   115,   267,  8624,     0,   169],
        [ 651

Metric Validation/Accuracy improved by 0.012 >= min_delta = 0.0. New best score: 0.984


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 20
ValidationEpoch/CM
 tensor([[43860,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 65531,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 53738,   264,   115,   267,  8762,     0,   169],
        [ 6524,   155,   650, 42027,  1365,     2,  2217,     0,   165],
        [  821,   133,   542,   736, 51639,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 55891,    13,     0,   175],
        [ 1148,   166, 10339,  4341,   349,   181, 36426,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 52722,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 65591]])
Epoch end: Train, epoch number: 19
TrainEpoch/CM
 tensor([[43860,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 65531,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 53738,   264,   115,   267,  8762,     0,   169],
        [ 652

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 21
ValidationEpoch/CM
 tensor([[46410,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 68811,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 56800,   266,   115,   267,  8878,     0,   169],
        [ 6528,   155,   657, 44589,  1365,     2,  2294,     0,   165],
        [  821,   133,   542,   736, 54354,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 58711,    13,     0,   175],
        [ 1148,   166, 10479,  4480,   349,   184, 38794,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 55367,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 68871]])
Epoch end: Train, epoch number: 20
TrainEpoch/CM
 tensor([[46410,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 68811,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 56800,   266,   115,   267,  8878,     0,   169],
        [ 652

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 22
ValidationEpoch/CM
 tensor([[48960,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 72091,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 59838,   267,   115,   267,  9019,     0,   169],
        [ 6532,   155,   664, 47079,  1365,     2,  2443,     0,   165],
        [  821,   133,   542,   736, 57069,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 61531,    13,     0,   175],
        [ 1148,   166, 10606,  4585,   349,   188, 41208,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 58012,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 72151]])
Epoch end: Train, epoch number: 21
TrainEpoch/CM
 tensor([[48960,   140,   469,  4314,  1308,     1,   850,     0,   159],
        [    0, 72091,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 59838,   267,   115,   267,  9019,     0,   169],
        [ 653

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 23
ValidationEpoch/CM
 tensor([[51509,   140,   469,  4314,  1308,     1,   851,     0,   159],
        [    0, 75371,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 62886,   269,   115,   267,  9149,     0,   169],
        [ 6535,   155,   667, 49655,  1365,     2,  2511,     0,   165],
        [  821,   133,   542,   736, 59784,    29,   347,     0,   151],
        [    0,   179,   255,     0,     0, 64351,    13,     0,   175],
        [ 1148,   166, 10729,  4702,   349,   189, 43617,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 60657,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 75431]])
Epoch end: Train, epoch number: 22
TrainEpoch/CM
 tensor([[51509,   140,   469,  4314,  1308,     1,   851,     0,   159],
        [    0, 75371,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 62886,   269,   115,   267,  9149,     0,   169],
        [ 653

Metric Validation/Accuracy improved by 0.001 >= min_delta = 0.0. New best score: 0.985


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 24
ValidationEpoch/CM
 tensor([[54056,   140,   469,  4317,  1308,     1,   851,     0,   159],
        [    0, 78651,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 66028,   269,   115,   267,  9187,     0,   169],
        [ 6535,   155,   669, 52283,  1365,     2,  2531,     0,   165],
        [  821,   133,   542,   736, 62499,    29,   347,     0,   151],
        [    0,   179,   257,     0,     0, 67169,    13,     0,   175],
        [ 1148,   166, 10866,  4820,   349,   189, 46012,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 63302,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 78711]])
Epoch end: Train, epoch number: 23
TrainEpoch/CM
 tensor([[54056,   140,   469,  4317,  1308,     1,   851,     0,   159],
        [    0, 78651,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 66028,   269,   115,   267,  9187,     0,   169],
        [ 653

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 25
ValidationEpoch/CM
 tensor([[56606,   140,   469,  4317,  1308,     1,   851,     0,   159],
        [    0, 81931,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 69084,   269,   115,   271,  9307,     0,   169],
        [ 6539,   155,   673, 54826,  1365,     2,  2630,     0,   165],
        [  821,   133,   542,   736, 65214,    29,   347,     0,   151],
        [    0,   179,   257,     0,     0, 69989,    13,     0,   175],
        [ 1148,   166, 10996,  4907,   349,   194, 48440,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 65947,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 81991]])
Epoch end: Train, epoch number: 24
TrainEpoch/CM
 tensor([[56606,   140,   469,  4317,  1308,     1,   851,     0,   159],
        [    0, 81931,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 69084,   269,   115,   271,  9307,     0,   169],
        [ 653

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 26
ValidationEpoch/CM
 tensor([[59152,   140,   469,  4320,  1308,     1,   852,     0,   159],
        [    0, 85211,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 72189,   269,   115,   271,  9382,     0,   169],
        [ 6545,   155,   674, 57415,  1365,     2,  2684,     0,   165],
        [  821,   133,   542,   736, 67929,    29,   347,     0,   151],
        [    0,   179,   259,     0,     0, 72807,    13,     0,   175],
        [ 1150,   166, 11188,  5031,   349,   194, 50772,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 68592,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 85271]])
Epoch end: Train, epoch number: 25
TrainEpoch/CM
 tensor([[59152,   140,   469,  4320,  1308,     1,   852,     0,   159],
        [    0, 85211,     0,     0,     0,     0,     2,     0,   185],
        [  196,   213, 72189,   269,   115,   271,  9382,     0,   169],
        [ 654

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 27
ValidationEpoch/CM
 tensor([[61423,   140,   470,  4576,  1320,     1,   862,     0,   159],
        [    0, 88490,     0,     0,     0,     0,     2,     1,   185],
        [  200,   213, 74947,   272,   124,   292,  9767,     0,   169],
        [ 6857,   155,   681, 59650,  1380,     2,  2765,     0,   165],
        [  835,   133,   548,   758, 70596,    29,   353,     0,   151],
        [    0,   179,   276,     0,     0, 75610,    13,     0,   175],
        [ 1231,   166, 11688,  5233,   362,   212, 52608,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 71237,   159],
        [    0,   122,    13,     0,     0,     0,     0,     0, 88551]])
Epoch end: Train, epoch number: 26
TrainEpoch/CM
 tensor([[61423,   140,   470,  4576,  1320,     1,   862,     0,   159],
        [    0, 88490,     0,     0,     0,     0,     2,     1,   185],
        [  200,   213, 74947,   272,   124,   292,  9767,     0,   169],
        [ 685

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 28
ValidationEpoch/CM
 tensor([[63961,   140,   470,  4586,  1320,     1,   864,     0,   159],
        [    0, 91769,     0,     0,     0,     0,     2,     2,   185],
        [  200,   213, 77973,   272,   124,   297,  9916,     0,   169],
        [ 6863,   155,   682, 62234,  1380,     2,  2824,     0,   165],
        [  835,   133,   548,   762, 73304,    29,   355,     1,   151],
        [    0,   182,   276,     0,     0, 78427,    13,     0,   175],
        [ 1235,   166, 11861,  5439,   362,   218, 54869,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 73882,   159],
        [    0,   122,    14,     0,     0,     0,     0,     0, 91830]])


Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 0.985. Signaling Trainer to stop.


Epoch end: Train, epoch number: 27
TrainEpoch/CM
 tensor([[63961,   140,   470,  4586,  1320,     1,   864,     0,   159],
        [    0, 91769,     0,     0,     0,     0,     2,     2,   185],
        [  200,   213, 77973,   272,   124,   297,  9916,     0,   169],
        [ 6863,   155,   682, 62234,  1380,     2,  2824,     0,   165],
        [  835,   133,   548,   762, 73304,    29,   355,     1,   151],
        [    0,   182,   276,     0,     0, 78427,    13,     0,   175],
        [ 1235,   166, 11861,  5439,   362,   218, 54869,     0,   144],
        [    0,   137,     0,     0,     0,     0,     3, 73882,   159],
        [    0,   122,    14,     0,     0,     0,     0,     0, 91830]])


In [14]:
model.eval()

MalwaresModelMLP(
  (train_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Train/
  )
  (val_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Validation/
  )
  (test_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Test/
  )
  (cm): MulticlassConfusionMatrix()
  (criterion): CrossEntropyLoss()
  (l1): Linear(in_features=305, out_features=30, bias=True)
  (l2): Linear(in_features=30, out_features=30, bias=True)
  (l3): Linear(in_features=30, out_features=9, bias=True)
)

In [23]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelMLP.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/lightning_logs/version_7/checkpoints/epoch=22-step=966.ckpt
tensor(0.9851, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[511,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0, 673,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0, 618,   0,   0,   0,  31,   0,   0],
        [  0,   0,   0, 519,   0,   0,   7,   0,   0],
        [  0,   0,   0,   0, 512,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 588,   0,   0,   0],
        [  0,   0,  18,  18,   0,   0, 460,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0, 550,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 649]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.9850842952728271
      Test/F1Score          0.9847362637519836
        Test/Loss          0.042185284197330475
     Test/Precision         0

[{'Test/Loss': 0.042185284197330475,
  'Test/Accuracy': 0.9850842952728271,
  'Test/Precision': 0.9848151803016663,
  'Test/Recall': 0.9850842952728271,
  'Test/F1Score': 0.9847362637519836,
  'TestEpoch/Accuracy': 0.9851495027542114,
  'TestEpoch/Precision': 0.984652578830719,
  'TestEpoch/Recall': 0.9851495027542114,
  'TestEpoch/F1Score': 0.9848780632019043}]