# Idea
Do some training

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import pickle

In [2]:
import sys
repo_base_path = Path("./../../").resolve()
assert str(repo_base_path).endswith("csg_is"), f"{repo_base_path} is not a valid path to the CSG_IS repository" 

sys.path.append(str(repo_base_path))

# from py_dataset import get_all_files_df
# from py_dataset import read_in_files
from py_dataset import feature_plotting
# from py_dataset import feature_selection
# from py_dataset import net_feature_engineering
# from py_dataset import entropy_feature_engineering
# from py_dataset.classes import DataSource
from py_dataset import sys_func



In [4]:
df = pd.read_csv('../data/all_df.csv')
df.set_index("timestamp", inplace=True)

In [7]:
df["label"].unique()

array(['1_normal', nan, '2_ransomware', '3_thetick', '4_bashlite',
       '5_httpbackdoor', '6_beurk', '7_backdoor', '8_bdvl', '9_xmrig'],
      dtype=object)

In [1]:
with open("rfe_selected_columns.npy","r") as f:
    col_str= f.read()
col_str

"'ext4:ext4_da_update_reserve_space_FLS_data','signal:signal_deliver','net:net_dev_xmit','sched:sched_process_exec_KERN_data','jbd2:jbd2_start_commit_KERN_data','tcp:tcp_probe_KERN_data','ext4:ext4_unlink_enter_RES_data','write_merge','sched:sched_stat_runtime','pkt_out','cache-references','ext4:ext4_free_inode_RES_data','armv7_cortex_a15/br_mis_pred/','iowrite','pkt_in','memory','write_kbs','connect','getppid','mkdir','getegid32','statfs64','geteuid32','recv','setitimer','fstat64','lgetxattr','pipe2','setgroups32','getuid32','label'"

In [2]:
cols = col_str.replace("'","").split(",")
cols

['ext4:ext4_da_update_reserve_space_FLS_data',
 'signal:signal_deliver',
 'net:net_dev_xmit',
 'sched:sched_process_exec_KERN_data',
 'jbd2:jbd2_start_commit_KERN_data',
 'tcp:tcp_probe_KERN_data',
 'ext4:ext4_unlink_enter_RES_data',
 'write_merge',
 'sched:sched_stat_runtime',
 'pkt_out',
 'cache-references',
 'ext4:ext4_free_inode_RES_data',
 'armv7_cortex_a15/br_mis_pred/',
 'iowrite',
 'pkt_in',
 'memory',
 'write_kbs',
 'connect',
 'getppid',
 'mkdir',
 'getegid32',
 'statfs64',
 'geteuid32',
 'recv',
 'setitimer',
 'fstat64',
 'lgetxattr',
 'pipe2',
 'setgroups32',
 'getuid32',
 'label']

In [10]:
df = df[cols]

### Preprocessings
- remove Null values
- drop timestamp
- labelEncode
- normalize

In [11]:
print(df.shape)
old_df = df.copy()
df.dropna(axis=0, how='any', inplace=True)

print(df.shape)

(43248, 31)
(26842, 31)


/tmp/ipykernel_136981/708996582.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(axis=0, how='any', inplace=True)


In [12]:
df.reset_index(inplace=True, drop=True)

In [13]:
label_encoder = sys_func.create_label_encoder_for_labels()
df['label'] = label_encoder.transform(df['label'])

/tmp/ipykernel_136981/3852457944.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = label_encoder.transform(df['label'])


In [14]:
df = feature_plotting.test_transform_all_to_numeric_columns(df)

In [15]:
cols_to_exclude_from_scaling = ["label"]
vectors = feature_plotting.minmax_scale_features(df,remove_outliers_iqr_all_columns=False,
                                                        cols_to_exclude_from_scaling=cols_to_exclude_from_scaling)
# print(vectors.shape)
# print(" with dropped null: ", vectors.dropna(axis=0, how='any', inplace=False).shape)

In [16]:
df["label"].unique(), vectors["label"].unique()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

### Setup

In [17]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomeDataset(Dataset):
    def __init__(self, some_df:pd.DataFrame):
        
        self.x = torch.tensor(some_df.drop(columns=["label"], inplace=False).values, dtype=torch.float32)
        self.labels = torch.tensor(some_df["label"].values, dtype=torch.uint8)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        # if torch.is_tensor(idx):
        #     idx = idx.tolist()
        # print(self.x[idx], self.labels[idx])
        return self.x[idx], self.labels[idx]

In [21]:
sys.path.append(str(repo_base_path  / "training"))

In [22]:
from mlp import MalwaresModelMLP
from torch.utils.data import DataLoader
import lightning
from sklearn.model_selection import train_test_split
from lightning import loggers as pl_loggers
from lightning.pytorch.callbacks.early_stopping import EarlyStopping
from lightning.pytorch.callbacks.model_checkpoint import ModelCheckpoint

# tensorboard = pl_loggers.TensorBoardLogger('./')

# split into train and val
train, val = train_test_split(vectors, test_size=0.2)

train_dataset = CustomeDataset(train)
train_dataloader = DataLoader(train_dataset, batch_size=500, shuffle=True, num_workers=7)

val_dataset = CustomeDataset(val)
val_dataloader = DataLoader(val_dataset, batch_size=500, shuffle=False, num_workers=7)

# trainer = lightning.Trainer(fast_dev_run=100)
monitor = "Validation/Accuracy"
early_stop_callback = EarlyStopping(monitor=monitor, patience=5, verbose=True, mode="max")
checkpoint_callback = ModelCheckpoint(save_top_k=1, monitor=monitor, mode="max")

trainer = lightning.Trainer(max_epochs=150, callbacks=[early_stop_callback, checkpoint_callback], enable_checkpointing=True) #logger=None, 


model = MalwaresModelMLP(input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [23]:
trainer.fit(model=model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                      | Params
------------------------------------------------------------
0 | train_metrics | MetricCollection          | 0     
1 | val_metrics   | MetricCollection          | 0     
2 | test_metrics  | MetricCollection          | 0     
3 | cm            | MulticlassConfusionMatrix | 0     
4 | criterion     | CrossEntropyLoss          | 0     
5 | l1            | Linear                    | 930   
6 | l2            | Linear                    | 930   
7 | l3            | Linear                    | 279   
------------------------------------------------------------
2.1 K     Trainable params
0         Non-trainable params
2.1 K     Total params
0.009     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 0
ValidationEpoch/CM
 tensor([[ 90,   0,   0,   0,   0,   0,   0,   0,   0],
        [  6,   0,   0,   0,   0, 130,   0,   0,   0],
        [149,   0,   0,   0,   0,   3,   0,   0,   0],
        [ 97,   0,   0,   0,   0,   0,   0,   0,   0],
        [104,   0,   0,   0,   0,   0,   0,   0,   0],
        [ 97,   0,   0,   0,   0,   0,   0,   0,   0],
        [106,   0,   0,   0,   0,   1,   0,   0,   0],
        [102,   0,   0,   0,   0,   0,   0,   0,   0],
        [115,   0,   0,   0,   0,   0,   0,   0,   0]])


/home/<User>/repos/csg_is/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (43) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 1
ValidationEpoch/CM
 tensor([[ 536,    0, 1304,  490,  296,    0,   14,    0,    0],
        [   7, 3223,    0,    0,    0,  186,    0,    0,    0],
        [ 280,    1, 3986,   26,   49,   42,   15,    0,    1],
        [ 535,    1, 1389,  457,  332,    0,   29,    0,    4],
        [ 570,    0, 1203,  215,  809,    6,   14,    0,    2],
        [ 142,   38, 1073,    0,    0, 1623,    0,   45,    0],
        [ 316,    0, 2132,  119,  136,   17,   37,    0,    0],
        [ 162,  588,   62,    0,    0,    0,    0, 1935,    0],
        [ 225,   84,  298,    0,    0,    1,    0,    0, 2787]])
Epoch end: Train, epoch number: 0
TrainEpoch/CM
 tensor([[ 536,    0, 1304,  490,  296,    0,   14,    0,    0],
        [   7, 3223,    0,    0,    0,  186,    0,    0,    0],
        [ 280,    1, 3986,   26,   49,   42,   15,    0,    1],
        [ 535,    1, 1389,  457,  332,    0,   29,    0,    4],
        [ 570,    0, 1203,  215,  809,    6,   14,    0,   

Metric Validation/Accuracy improved. New best score: 0.703


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 2
ValidationEpoch/CM
 tensor([[1626,    0, 1363, 1488,  567,    0,  146,    0,    0],
        [   7, 6503,    0,    0,    0,  186,    0,    0,    0],
        [ 312,    1, 7749,   71,   64,   72,  378,    0,    1],
        [1390,    1, 1463, 1570,  734,    0,  230,    0,    9],
        [ 718,    0, 1227,  409, 3101,   13,   64,    0,    2],
        [ 142,   41, 1084,    0,    0, 4433,    0,   45,    0],
        [ 525,    0, 3625,  447,  240,   30,  540,    0,    0],
        [ 162,  588,   62,    0,    0,    0,    0, 4580,    0],
        [ 225,   84,  298,    0,    0,    1,    0,    0, 6067]])


Metric Validation/Accuracy improved by 0.084 >= min_delta = 0.0. New best score: 0.787


Epoch end: Train, epoch number: 1
TrainEpoch/CM
 tensor([[1626,    0, 1363, 1488,  567,    0,  146,    0,    0],
        [   7, 6503,    0,    0,    0,  186,    0,    0,    0],
        [ 312,    1, 7749,   71,   64,   72,  378,    0,    1],
        [1390,    1, 1463, 1570,  734,    0,  230,    0,    9],
        [ 718,    0, 1227,  409, 3101,   13,   64,    0,    2],
        [ 142,   41, 1084,    0,    0, 4433,    0,   45,    0],
        [ 525,    0, 3625,  447,  240,   30,  540,    0,    0],
        [ 162,  588,   62,    0,    0,    0,    0, 4580,    0],
        [ 225,   84,  298,    0,    0,    1,    0,    0, 6067]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 3
ValidationEpoch/CM
 tensor([[ 3248,     0,  1369,  2272,   599,     0,   252,     0,     0],
        [    7,  9782,     0,     0,     0,   186,     0,     0,     1],
        [  319,     1, 11531,   101,    65,    96,   782,     0,     1],
        [ 2318,     1,  1466,  2936,   811,     0,   501,     0,    14],
        [  799,     0,  1232,   504,  5612,    14,    86,     0,     2],
        [  142,    46,  1089,     0,     0,  7247,     0,    45,     0],
        [  667,     0,  4957,   790,   246,    36,  1360,     0,     1],
        [  162,   588,    62,     0,     0,     0,     0,  7225,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0,  9347]])


Metric Validation/Accuracy improved by 0.037 >= min_delta = 0.0. New best score: 0.824


Epoch end: Train, epoch number: 2
TrainEpoch/CM
 tensor([[ 3248,     0,  1369,  2272,   599,     0,   252,     0,     0],
        [    7,  9782,     0,     0,     0,   186,     0,     0,     1],
        [  319,     1, 11531,   101,    65,    96,   782,     0,     1],
        [ 2318,     1,  1466,  2936,   811,     0,   501,     0,    14],
        [  799,     0,  1232,   504,  5612,    14,    86,     0,     2],
        [  142,    46,  1089,     0,     0,  7247,     0,    45,     0],
        [  667,     0,  4957,   790,   246,    36,  1360,     0,     1],
        [  162,   588,    62,     0,     0,     0,     0,  7225,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0,  9347]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 4
ValidationEpoch/CM
 tensor([[ 5205,     0,  1369,  2786,   613,     0,   317,     0,     0],
        [    7, 13059,     0,     0,     2,   187,     0,     0,     1],
        [  322,     1, 15326,   122,    69,   111,  1192,     0,     1],
        [ 3190,     1,  1466,  4462,   832,     0,   727,     0,    19],
        [  837,     0,  1237,   590,  8182,    14,   102,     0,     2],
        [  142,    51,  1103,     0,     0, 10052,     0,    45,     0],
        [  784,     3,  6170,  1134,   249,    38,  2327,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0,  9870,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0, 12627]])


Metric Validation/Accuracy improved by 0.021 >= min_delta = 0.0. New best score: 0.845


Epoch end: Train, epoch number: 3
TrainEpoch/CM
 tensor([[ 5205,     0,  1369,  2786,   613,     0,   317,     0,     0],
        [    7, 13059,     0,     0,     2,   187,     0,     0,     1],
        [  322,     1, 15326,   122,    69,   111,  1192,     0,     1],
        [ 3190,     1,  1466,  4462,   832,     0,   727,     0,    19],
        [  837,     0,  1237,   590,  8182,    14,   102,     0,     2],
        [  142,    51,  1103,     0,     0, 10052,     0,    45,     0],
        [  784,     3,  6170,  1134,   249,    38,  2327,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0,  9870,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0, 12627]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 5
ValidationEpoch/CM
 tensor([[ 7398,     0,  1369,  3080,   622,     0,   371,     0,     0],
        [    7, 16335,     0,     0,     4,   189,     0,     0,     1],
        [  322,     1, 19173,   136,    72,   132,  1555,     0,     1],
        [ 3664,     1,  1466,  6413,   841,     0,   938,     0,    24],
        [  854,     0,  1242,   662, 10789,    14,   116,     0,     2],
        [  142,    56,  1115,     0,     0, 12859,     0,    45,     0],
        [  847,     6,  7366,  1529,   254,    42,  3311,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 12515,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0, 15907]])


Metric Validation/Accuracy improved by 0.037 >= min_delta = 0.0. New best score: 0.882


Epoch end: Train, epoch number: 4
TrainEpoch/CM
 tensor([[ 7398,     0,  1369,  3080,   622,     0,   371,     0,     0],
        [    7, 16335,     0,     0,     4,   189,     0,     0,     1],
        [  322,     1, 19173,   136,    72,   132,  1555,     0,     1],
        [ 3664,     1,  1466,  6413,   841,     0,   938,     0,    24],
        [  854,     0,  1242,   662, 10789,    14,   116,     0,     2],
        [  142,    56,  1115,     0,     0, 12859,     0,    45,     0],
        [  847,     6,  7366,  1529,   254,    42,  3311,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 12515,     0],
        [  225,    84,   298,     0,     0,     1,     0,     0, 15907]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 6
ValidationEpoch/CM
 tensor([[ 9753,     0,  1369,  3229,   628,     0,   411,     0,     0],
        [    7, 19610,     0,     0,     5,   193,     0,     0,     1],
        [  322,     1, 22981,   147,    72,   149,  1967,     0,     1],
        [ 3871,     1,  1466,  8689,   848,     0,  1094,     0,    28],
        [  859,     0,  1247,   706, 13435,    14,   131,     0,     2],
        [  142,    63,  1130,     0,     0, 15661,     0,    45,     0],
        [  902,     7,  8509,  1946,   259,    49,  4333,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 15160,     0],
        [  225,    85,   298,     0,     0,     1,     0,     0, 19186]])


Metric Validation/Accuracy improved by 0.023 >= min_delta = 0.0. New best score: 0.904


Epoch end: Train, epoch number: 5
TrainEpoch/CM
 tensor([[ 9753,     0,  1369,  3229,   628,     0,   411,     0,     0],
        [    7, 19610,     0,     0,     5,   193,     0,     0,     1],
        [  322,     1, 22981,   147,    72,   149,  1967,     0,     1],
        [ 3871,     1,  1466,  8689,   848,     0,  1094,     0,    28],
        [  859,     0,  1247,   706, 13435,    14,   131,     0,     2],
        [  142,    63,  1130,     0,     0, 15661,     0,    45,     0],
        [  902,     7,  8509,  1946,   259,    49,  4333,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 15160,     0],
        [  225,    85,   298,     0,     0,     1,     0,     0, 19186]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 7
ValidationEpoch/CM
 tensor([[12149,     0,  1369,  3347,   631,     0,   444,     0,     0],
        [    7, 22890,     0,     0,     5,   193,     0,     0,     1],
        [  322,     1, 26782,   151,    76,   164,  2391,     0,     1],
        [ 3977,     1,  1466, 11080,   852,     0,  1238,     0,    33],
        [  862,     0,  1249,   732, 16108,    14,   142,     0,     2],
        [  142,    68,  1143,     0,     0, 18467,     0,    45,     0],
        [  946,     7,  9650,  2330,   266,    55,  5401,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 17805,     0],
        [  225,    85,   298,     0,     5,     1,     0,     0, 22461]])
Epoch end: Train, epoch number: 6
TrainEpoch/CM
 tensor([[12149,     0,  1369,  3347,   631,     0,   444,     0,     0],
        [    7, 22890,     0,     0,     5,   193,     0,     0,     1],
        [  322,     1, 26782,   151,    76,   164,  2391,     0,     1],
        [ 3977,

Metric Validation/Accuracy improved by 0.004 >= min_delta = 0.0. New best score: 0.909


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 8
ValidationEpoch/CM
 tensor([[14595,     0,  1369,  3421,   634,     0,   471,     0,     0],
        [    7, 26169,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 30560,   151,    78,   171,  2852,     0,     1],
        [ 4044,     1,  1466, 13521,   854,     0,  1373,     0,    38],
        [  862,     0,  1250,   745, 18798,    14,   153,     0,     2],
        [  142,    71,  1155,     0,     0, 21276,     0,    45,     0],
        [  990,     7, 10715,  2687,   267,    61,  6578,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 20450,     0],
        [  225,    85,   298,     0,    10,     1,     0,     0, 25736]])
Epoch end: Train, epoch number: 7
TrainEpoch/CM
 tensor([[14595,     0,  1369,  3421,   634,     0,   471,     0,     0],
        [    7, 26169,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 30560,   151,    78,   171,  2852,     0,     1],
        [ 4044,

Metric Validation/Accuracy improved by 0.011 >= min_delta = 0.0. New best score: 0.920


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 9
ValidationEpoch/CM
 tensor([[17066,     0,  1369,  3482,   634,     0,   489,     0,     0],
        [    7, 29449,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 34371,   151,    78,   181,  3279,     0,     1],
        [ 4081,     1,  1466, 15988,   858,     0,  1510,     0,    43],
        [  862,     0,  1252,   746, 21501,    14,   162,     0,     2],
        [  142,    71,  1167,     0,     0, 24088,     0,    45,     0],
        [ 1020,     7, 11769,  3031,   267,    66,  7795,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 23095,     0],
        [  225,    85,   298,     0,    12,     1,     0,     0, 29014]])
Epoch end: Train, epoch number: 8
TrainEpoch/CM
 tensor([[17066,     0,  1369,  3482,   634,     0,   489,     0,     0],
        [    7, 29449,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 34371,   151,    78,   181,  3279,     0,     1],
        [ 4081,

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 10
ValidationEpoch/CM
 tensor([[19556,     0,  1369,  3521,   634,     0,   510,     0,     0],
        [    7, 32729,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 38185,   151,    81,   186,  3705,     0,     1],
        [ 4097,     1,  1466, 18484,   859,     0,  1642,     0,    48],
        [  862,     0,  1254,   751, 24200,    14,   171,     0,     2],
        [  142,    71,  1176,     0,     0, 26901,     2,    45,     0],
        [ 1051,     7, 12745,  3345,   267,    69,  9121,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 25740,     0],
        [  225,    85,   298,     0,    12,     1,     0,     0, 32294]])


Metric Validation/Accuracy improved by 0.007 >= min_delta = 0.0. New best score: 0.927


Epoch end: Train, epoch number: 9
TrainEpoch/CM
 tensor([[19556,     0,  1369,  3521,   634,     0,   510,     0,     0],
        [    7, 32729,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 38185,   151,    81,   186,  3705,     0,     1],
        [ 4097,     1,  1466, 18484,   859,     0,  1642,     0,    48],
        [  862,     0,  1254,   751, 24200,    14,   171,     0,     2],
        [  142,    71,  1176,     0,     0, 26901,     2,    45,     0],
        [ 1051,     7, 12745,  3345,   267,    69,  9121,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 25740,     0],
        [  225,    85,   298,     0,    12,     1,     0,     0, 32294]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 11
ValidationEpoch/CM
 tensor([[22051,     0,  1369,  3558,   634,     0,   528,     0,     0],
        [    7, 36009,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 41971,   151,    84,   190,  4160,     0,     1],
        [ 4109,     1,  1466, 21016,   860,     0,  1742,     0,    53],
        [  862,     0,  1256,   758, 26902,    14,   175,     0,     2],
        [  142,    71,  1179,     0,     0, 29720,     4,    45,     0],
        [ 1069,     7, 13590,  3688,   268,    77, 10556,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 28385,     0],
        [  225,    85,   298,     0,    14,     1,     0,     0, 35572]])


Metric Validation/Accuracy improved by 0.008 >= min_delta = 0.0. New best score: 0.935


Epoch end: Train, epoch number: 10
TrainEpoch/CM
 tensor([[22051,     0,  1369,  3558,   634,     0,   528,     0,     0],
        [    7, 36009,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 41971,   151,    84,   190,  4160,     0,     1],
        [ 4109,     1,  1466, 21016,   860,     0,  1742,     0,    53],
        [  862,     0,  1256,   758, 26902,    14,   175,     0,     2],
        [  142,    71,  1179,     0,     0, 29720,     4,    45,     0],
        [ 1069,     7, 13590,  3688,   268,    77, 10556,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 28385,     0],
        [  225,    85,   298,     0,    14,     1,     0,     0, 35572]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 12
ValidationEpoch/CM
 tensor([[24561,     0,  1369,  3580,   634,     0,   546,     0,     0],
        [    8, 39288,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 45458,   151,    86,   191,  4918,     0,     1],
        [ 4116,     1,  1466, 23541,   863,     0,  1852,     0,    58],
        [  862,     0,  1256,   768, 29604,    14,   178,     0,     2],
        [  142,    71,  1179,     0,     0, 32538,    10,    45,     0],
        [ 1087,     7, 14258,  3968,   268,    84, 12233,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 31030,     0],
        [  225,    85,   298,     1,    14,     1,     0,     0, 38851]])
Epoch end: Train, epoch number: 11
TrainEpoch/CM
 tensor([[24561,     0,  1369,  3580,   634,     0,   546,     0,     0],
        [    8, 39288,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 45458,   151,    86,   191,  4918,     0,     1],
        [ 411

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 13
ValidationEpoch/CM
 tensor([[27067,     0,  1369,  3607,   634,     0,   563,     0,     0],
        [    8, 42568,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 49288,   151,    86,   195,  5332,     0,     1],
        [ 4145,     1,  1466, 26003,   863,     0,  2006,     0,    63],
        [  862,     0,  1256,   773, 32313,    14,   179,     0,     2],
        [  142,    71,  1179,     0,     0, 35361,    11,    45,     0],
        [ 1109,     7, 15059,  4220,   268,    90, 13802,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 33675,     0],
        [  225,    85,   298,     4,    17,     1,     0,     0, 42125]])
Epoch end: Train, epoch number: 12
TrainEpoch/CM
 tensor([[27067,     0,  1369,  3607,   634,     0,   563,     0,     0],
        [    8, 42568,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 49288,   151,    86,   195,  5332,     0,     1],
        [ 414

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 14
ValidationEpoch/CM
 tensor([[29579,     0,  1369,  3631,   634,     0,   577,     0,     0],
        [    8, 45848,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 53132,   151,    86,   196,  5735,     0,     1],
        [ 4147,     1,  1466, 28560,   863,     0,  2092,     0,    68],
        [  862,     0,  1256,   775, 35026,    14,   179,     0,     2],
        [  142,    71,  1179,     0,     0, 38183,    13,    45,     0],
        [ 1117,     7, 15737,  4464,   268,    96, 15516,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 36320,     0],
        [  225,    85,   298,     6,    17,     1,     0,     0, 45403]])


Metric Validation/Accuracy improved by 0.018 >= min_delta = 0.0. New best score: 0.953


Epoch end: Train, epoch number: 13
TrainEpoch/CM
 tensor([[29579,     0,  1369,  3631,   634,     0,   577,     0,     0],
        [    8, 45848,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 53132,   151,    86,   196,  5735,     0,     1],
        [ 4147,     1,  1466, 28560,   863,     0,  2092,     0,    68],
        [  862,     0,  1256,   775, 35026,    14,   179,     0,     2],
        [  142,    71,  1179,     0,     0, 38183,    13,    45,     0],
        [ 1117,     7, 15737,  4464,   268,    96, 15516,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 36320,     0],
        [  225,    85,   298,     6,    17,     1,     0,     0, 45403]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 15
ValidationEpoch/CM
 tensor([[32097,     0,  1369,  3648,   634,     0,   592,     0,     0],
        [    8, 49128,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 57034,   151,    86,   196,  6081,     0,     1],
        [ 4150,     1,  1466, 31124,   863,     0,  2170,     0,    73],
        [  862,     0,  1256,   776, 37739,    14,   180,     0,     2],
        [  142,    72,  1179,     0,     0, 41001,    18,    45,     0],
        [ 1127,     7, 16352,  4705,   268,   101, 17295,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 38965,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 48680]])
Epoch end: Train, epoch number: 14
TrainEpoch/CM
 tensor([[32097,     0,  1369,  3648,   634,     0,   592,     0,     0],
        [    8, 49128,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 57034,   151,    86,   196,  6081,     0,     1],
        [ 415

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 16
ValidationEpoch/CM
 tensor([[34616,     0,  1369,  3665,   634,     0,   606,     0,     0],
        [    9, 52407,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 60964,   151,    86,   197,  6398,     0,     1],
        [ 4157,     1,  1466, 33674,   867,     0,  2258,     0,    74],
        [  862,     0,  1256,   780, 40450,    14,   180,     0,     2],
        [  142,    72,  1179,     0,     0, 43819,    24,    45,     0],
        [ 1142,     7, 16903,  4919,   268,   107, 19159,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 41610,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 51960]])


Metric Validation/Accuracy improved by 0.005 >= min_delta = 0.0. New best score: 0.959


Epoch end: Train, epoch number: 15
TrainEpoch/CM
 tensor([[34616,     0,  1369,  3665,   634,     0,   606,     0,     0],
        [    9, 52407,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 60964,   151,    86,   197,  6398,     0,     1],
        [ 4157,     1,  1466, 33674,   867,     0,  2258,     0,    74],
        [  862,     0,  1256,   780, 40450,    14,   180,     0,     2],
        [  142,    72,  1179,     0,     0, 43819,    24,    45,     0],
        [ 1142,     7, 16903,  4919,   268,   107, 19159,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 41610,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 51960]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 17
ValidationEpoch/CM
 tensor([[37134,     0,  1369,  3683,   634,     0,   620,     0,     0],
        [    9, 55687,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 64930,   151,    86,   198,  6679,     0,     1],
        [ 4166,     1,  1466, 36229,   871,     0,  2339,     0,    75],
        [  862,     0,  1256,   782, 43160,    14,   183,     0,     2],
        [  142,    76,  1179,     0,     0, 46631,    32,    45,     0],
        [ 1159,     7, 17492,  5129,   268,   114, 20986,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 44255,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 55240]])
Epoch end: Train, epoch number: 16
TrainEpoch/CM
 tensor([[37134,     0,  1369,  3683,   634,     0,   620,     0,     0],
        [    9, 55687,     1,     0,     5,   193,     0,     0,     1],
        [  322,     1, 64930,   151,    86,   198,  6679,     0,     1],
        [ 416

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 18
ValidationEpoch/CM
 tensor([[39645,     0,  1369,  3704,   634,     0,   638,     0,     0],
        [    9, 58966,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 68856,   154,    86,   201,  6995,     0,     1],
        [ 4172,     1,  1466, 38793,   878,     0,  2412,     0,    75],
        [  862,     0,  1256,   788, 45869,    14,   183,     0,     2],
        [  142,    76,  1179,     0,     0, 49454,    33,    45,     0],
        [ 1170,     7, 18109,  5337,   268,   119, 22795,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 46900,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 58520]])
Epoch end: Train, epoch number: 17
TrainEpoch/CM
 tensor([[39645,     0,  1369,  3704,   634,     0,   638,     0,     0],
        [    9, 58966,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 68856,   154,    86,   201,  6995,     0,     1],
        [ 417

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 19
ValidationEpoch/CM
 tensor([[42164,     0,  1369,  3723,   634,     0,   650,     0,     0],
        [    9, 62246,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 72801,   154,    88,   203,  7294,     0,     1],
        [ 4175,     1,  1466, 41348,   883,     0,  2499,     0,    75],
        [  862,     0,  1257,   788, 48582,    14,   184,     0,     2],
        [  142,    76,  1179,     0,     0, 52274,    37,    45,     0],
        [ 1181,     7, 18543,  5516,   268,   126, 24814,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 49545,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 61800]])
Epoch end: Train, epoch number: 18
TrainEpoch/CM
 tensor([[42164,     0,  1369,  3723,   634,     0,   650,     0,     0],
        [    9, 62246,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 72801,   154,    88,   203,  7294,     0,     1],
        [ 417

Metric Validation/Accuracy improved by 0.006 >= min_delta = 0.0. New best score: 0.965


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 20
ValidationEpoch/CM
 tensor([[44683,     0,  1369,  3742,   634,     0,   662,     0,     0],
        [    9, 65526,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 76768,   154,    90,   203,  7573,     0,     1],
        [ 4180,     1,  1466, 43902,   888,     0,  2585,     0,    75],
        [  862,     0,  1258,   788, 51295,    14,   185,     0,     2],
        [  142,    76,  1179,     0,     0, 55098,    37,    45,     0],
        [ 1196,     7, 18992,  5693,   268,   134, 26815,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 52190,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 65080]])
Epoch end: Train, epoch number: 19
TrainEpoch/CM
 tensor([[44683,     0,  1369,  3742,   634,     0,   662,     0,     0],
        [    9, 65526,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 76768,   154,    90,   203,  7573,     0,     1],
        [ 418

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 21
ValidationEpoch/CM
 tensor([[47210,     0,  1369,  3757,   634,     0,   670,     0,     0],
        [    9, 68806,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 80744,   157,    90,   204,  7841,     0,     1],
        [ 4182,     1,  1469, 46479,   896,     0,  2645,     0,    75],
        [  862,     0,  1259,   788, 54008,    14,   186,     0,     2],
        [  142,    76,  1179,     0,     0, 57919,    40,    45,     0],
        [ 1209,     7, 19386,  5871,   268,   138, 28876,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 54835,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 68360]])
Epoch end: Train, epoch number: 20
TrainEpoch/CM
 tensor([[47210,     0,  1369,  3757,   634,     0,   670,     0,     0],
        [    9, 68806,     1,     0,     5,   194,     0,     0,     1],
        [  322,     1, 80744,   157,    90,   204,  7841,     0,     1],
        [ 418

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 22
ValidationEpoch/CM
 tensor([[49736,     0,  1369,  3774,   634,     0,   677,     0,     0],
        [    9, 72085,     1,     0,     5,   194,     0,     1,     1],
        [  322,     1, 84722,   158,    90,   204,  8110,     0,     1],
        [ 4186,     1,  1470, 49049,   901,     0,  2715,     0,    75],
        [  862,     0,  1262,   788, 56720,    14,   186,     0,     2],
        [  142,    78,  1179,     0,     0, 60737,    44,    45,     0],
        [ 1220,     7, 19757,  6041,   268,   142, 30970,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 57480,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 71640]])


Metric Validation/Accuracy improved by 0.001 >= min_delta = 0.0. New best score: 0.965


Epoch end: Train, epoch number: 21
TrainEpoch/CM
 tensor([[49736,     0,  1369,  3774,   634,     0,   677,     0,     0],
        [    9, 72085,     1,     0,     5,   194,     0,     1,     1],
        [  322,     1, 84722,   158,    90,   204,  8110,     0,     1],
        [ 4186,     1,  1470, 49049,   901,     0,  2715,     0,    75],
        [  862,     0,  1262,   788, 56720,    14,   186,     0,     2],
        [  142,    78,  1179,     0,     0, 60737,    44,    45,     0],
        [ 1220,     7, 19757,  6041,   268,   142, 30970,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 57480,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 71640]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 23
ValidationEpoch/CM
 tensor([[52260,     0,  1369,  3790,   634,     0,   687,     0,     0],
        [    9, 75364,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 88728,   160,    91,   204,  8349,     0,     1],
        [ 4186,     1,  1472, 51621,   906,     0,  2786,     0,    75],
        [  862,     0,  1265,   789, 59431,    14,   186,     0,     2],
        [  142,    78,  1179,     0,     0, 63560,    45,    45,     0],
        [ 1231,     7, 20134,  6188,   268,   145, 33082,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 60125,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 74920]])
Epoch end: Train, epoch number: 22
TrainEpoch/CM
 tensor([[52260,     0,  1369,  3790,   634,     0,   687,     0,     0],
        [    9, 75364,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 88728,   160,    91,   204,  8349,     0,     1],
        [ 418

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 24
ValidationEpoch/CM
 tensor([[54787,     0,  1369,  3806,   634,     0,   694,     0,     0],
        [    9, 78644,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 92742,   165,    91,   205,  8577,     0,     1],
        [ 4196,     1,  1474, 54145,   913,     0,  2893,     0,    75],
        [  862,     0,  1267,   791, 62142,    14,   186,     0,     2],
        [  142,    78,  1179,     0,     0, 66382,    47,    45,     0],
        [ 1248,     7, 20533,  6322,   268,   148, 35179,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 62770,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 78200]])
Epoch end: Train, epoch number: 23
TrainEpoch/CM
 tensor([[54787,     0,  1369,  3806,   634,     0,   694,     0,     0],
        [    9, 78644,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 92742,   165,    91,   205,  8577,     0,     1],
        [ 419

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 25
ValidationEpoch/CM
 tensor([[57310,     0,  1369,  3821,   634,     0,   704,     0,     2],
        [    9, 81924,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 96747,   167,    91,   205,  8818,     0,     1],
        [ 4200,     1,  1478, 56642,   919,     0,  3032,     0,    75],
        [  862,     0,  1268,   793, 64853,    14,   187,     0,     2],
        [  142,    78,  1179,     0,     0, 69206,    47,    45,     0],
        [ 1260,     7, 20897,  6451,   268,   149, 37323,     0,     2],
        [  162,   588,    62,     0,     0,     0,     0, 65415,     0],
        [  225,    85,   298,     7,    17,     1,     2,     0, 81480]])
Epoch end: Train, epoch number: 24
TrainEpoch/CM
 tensor([[57310,     0,  1369,  3821,   634,     0,   704,     0,     2],
        [    9, 81924,     1,     0,     5,   194,     0,     2,     1],
        [  322,     1, 96747,   167,    91,   205,  8818,     0,     1],
        [ 420

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 26
ValidationEpoch/CM
 tensor([[ 59838,      0,   1369,   3837,    634,      0,    710,      0,      2],
        [     9,  85204,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 100770,    171,     91,    207,   9037,      0,      1],
        [  4207,      1,   1479,  59184,    924,      0,   3127,      0,     75],
        [   862,      0,   1270,    793,  67565,     14,    188,      0,      2],
        [   142,     78,   1179,      0,      0,  72029,     48,     45,      0],
        [  1273,      7,  21293,   6585,    268,    153,  39426,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  68060,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  84760]])
Epoch end: Train, epoch number: 25
TrainEpoch/CM
 tensor([[ 59838,      0,   1369,   3837,    634,      0,    710,      0,      2],
        [     9,  85204,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 27
ValidationEpoch/CM
 tensor([[ 62366,      0,   1369,   3854,    634,      0,    715,      0,      2],
        [     9,  88484,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 104729,    175,     91,    207,   9322,      0,      1],
        [  4210,      1,   1484,  61731,    925,      0,   3221,      0,     75],
        [   862,      0,   1274,    794,  70272,     14,    191,      0,      2],
        [   142,     78,   1179,      0,      0,  74852,     49,     45,      0],
        [  1280,      7,  21623,   6703,    268,    155,  41619,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  70705,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  88040]])
Epoch end: Train, epoch number: 26
TrainEpoch/CM
 tensor([[ 62366,      0,   1369,   3854,    634,      0,    715,      0,      2],
        [     9,  88484,      1,      0,      5,    194,      0,     

Metric Validation/Accuracy improved by 0.007 >= min_delta = 0.0. New best score: 0.973


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 28
ValidationEpoch/CM
 tensor([[ 64893,      0,   1369,   3871,    634,      0,    721,      0,      2],
        [     9,  91764,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 108721,    178,     93,    207,   9573,      0,      1],
        [  4214,      1,   1486,  64302,    926,      0,   3293,      0,     75],
        [   862,      0,   1276,    794,  72985,     14,    191,      0,      2],
        [   142,     78,   1179,      0,      0,  77676,     49,     45,      0],
        [  1293,      7,  21912,   6832,    268,    158,  43835,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  73350,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  91320]])
Epoch end: Train, epoch number: 27
TrainEpoch/CM
 tensor([[ 64893,      0,   1369,   3871,    634,      0,    721,      0,      2],
        [     9,  91764,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 29
ValidationEpoch/CM
 tensor([[ 67429,      0,   1369,   3885,    634,      0,    721,      0,      2],
        [     9,  95044,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 112755,    180,     93,    207,   9785,      0,      1],
        [  4218,      1,   1492,  66863,    926,      0,   3372,      0,     75],
        [   862,      0,   1278,    794,  75697,     14,    192,      0,      2],
        [   142,     78,   1179,      0,      0,  80500,     49,     45,      0],
        [  1303,      7,  22211,   6937,    268,    158,  46071,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  75995,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  94600]])


Metric Validation/Accuracy improved by 0.004 >= min_delta = 0.0. New best score: 0.977


Epoch end: Train, epoch number: 28
TrainEpoch/CM
 tensor([[ 67429,      0,   1369,   3885,    634,      0,    721,      0,      2],
        [     9,  95044,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 112755,    180,     93,    207,   9785,      0,      1],
        [  4218,      1,   1492,  66863,    926,      0,   3372,      0,     75],
        [   862,      0,   1278,    794,  75697,     14,    192,      0,      2],
        [   142,     78,   1179,      0,      0,  80500,     49,     45,      0],
        [  1303,      7,  22211,   6937,    268,    158,  46071,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  75995,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  94600]])


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 30
ValidationEpoch/CM
 tensor([[ 69963,      0,   1369,   3899,    634,      0,    723,      0,      2],
        [     9,  98324,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 116780,    182,     93,    208,  10005,      0,      1],
        [  4219,      1,   1495,  69417,    926,      0,   3464,      0,     75],
        [   862,      0,   1280,    795,  78409,     14,    192,      0,      2],
        [   142,     78,   1179,      0,      0,  83324,     49,     45,      0],
        [  1310,      7,  22500,   7041,    268,    158,  48321,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  78640,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0,  97880]])
Epoch end: Train, epoch number: 29
TrainEpoch/CM
 tensor([[ 69963,      0,   1369,   3899,    634,      0,    723,      0,      2],
        [     9,  98324,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 31
ValidationEpoch/CM
 tensor([[ 72497,      0,   1369,   3911,    634,      0,    727,      0,      2],
        [     9, 101604,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 120822,    184,     93,    208,  10209,      0,      1],
        [  4224,      1,   1497,  71979,    927,      0,   3544,      0,     75],
        [   862,      0,   1283,    795,  81121,     14,    192,      0,      2],
        [   142,     78,   1179,      0,      0,  86148,     49,     45,      0],
        [  1318,      7,  22776,   7156,    268,    159,  50571,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  81285,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0, 101160]])
Epoch end: Train, epoch number: 30
TrainEpoch/CM
 tensor([[ 72497,      0,   1369,   3911,    634,      0,    727,      0,      2],
        [     9, 101604,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 32
ValidationEpoch/CM
 tensor([[ 75023,      0,   1369,   3929,    634,      0,    733,      0,      2],
        [     9, 104884,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 124802,    187,     93,    208,  10474,      0,      1],
        [  4232,      1,   1501,  74541,    927,      0,   3620,      0,     75],
        [   862,      0,   1284,    796,  83833,     14,    193,      0,      2],
        [   142,     78,   1179,      0,      0,  88972,     49,     45,      0],
        [  1332,      7,  23047,   7291,    268,    160,  52800,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  83930,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0, 104440]])
Epoch end: Train, epoch number: 31
TrainEpoch/CM
 tensor([[ 75023,      0,   1369,   3929,    634,      0,    733,      0,      2],
        [     9, 104884,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 33
ValidationEpoch/CM
 tensor([[ 77557,      0,   1369,   3943,    634,      0,    735,      0,      2],
        [     9, 108164,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 128820,    189,     93,    208,  10702,      0,      1],
        [  4236,      1,   1504,  77108,    927,      0,   3696,      0,     75],
        [   862,      0,   1288,    797,  86542,     14,    194,      0,      2],
        [   142,     78,   1179,      0,      0,  91796,     49,     45,      0],
        [  1340,      7,  23297,   7402,    268,    161,  55080,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  86575,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0, 107720]])
Epoch end: Train, epoch number: 32
TrainEpoch/CM
 tensor([[ 77557,      0,   1369,   3943,    634,      0,    735,      0,      2],
        [     9, 108164,      1,      0,      5,    194,      0,     

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch end: Validation, epoch number: 34
ValidationEpoch/CM
 tensor([[ 80085,      0,   1369,   3955,    634,      0,    745,      0,      2],
        [     9, 111444,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 132886,    190,     94,    208,  10882,      0,      1],
        [  4241,      1,   1510,  79660,    927,      0,   3783,      0,     75],
        [   862,      0,   1290,    797,  89255,     14,    194,      0,      2],
        [   142,     78,   1179,      0,      0,  94620,     49,     45,      0],
        [  1350,      7,  23572,   7500,    268,    162,  57346,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  89220,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0, 111000]])


Monitored metric Validation/Accuracy did not improve in the last 5 records. Best score: 0.977. Signaling Trainer to stop.


Epoch end: Train, epoch number: 33
TrainEpoch/CM
 tensor([[ 80085,      0,   1369,   3955,    634,      0,    745,      0,      2],
        [     9, 111444,      1,      0,      5,    194,      0,      2,      1],
        [   322,      1, 132886,    190,     94,    208,  10882,      0,      1],
        [  4241,      1,   1510,  79660,    927,      0,   3783,      0,     75],
        [   862,      0,   1290,    797,  89255,     14,    194,      0,      2],
        [   142,     78,   1179,      0,      0,  94620,     49,     45,      0],
        [  1350,      7,  23572,   7500,    268,    162,  57346,      0,      2],
        [   162,    588,     62,      0,      0,      0,      0,  89220,      0],
        [   225,     85,    298,      7,     17,      1,      2,      0, 111000]])


In [24]:
model.eval()

MalwaresModelMLP(
  (train_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Train/
  )
  (val_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Validation/
  )
  (test_metrics): MetricCollection(
    (MulticlassAccuracy): MulticlassAccuracy()
    (MulticlassPrecision): MulticlassPrecision()
    (MulticlassRecall): MulticlassRecall()
    (MulticlassF1Score): MulticlassF1Score(),
    prefix=Test/
  )
  (cm): MulticlassConfusionMatrix()
  (criterion): CrossEntropyLoss()
  (l1): Linear(in_features=30, out_features=30, bias=True)
  (l2): Linear(in_features=30, out_features=30, bias=True)
  (l3): Linear(in_features=30, out_features=9, bias=True)
)

In [25]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelMLP.load_from_checkpoint(checkpoint_callback.best_model_path, input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/sklearn_linear/lightning_logs/version_5/checkpoints/epoch=28-step=1247.ckpt
tensor(0.9767, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[513,   0,   0,   5,   0,   0,   0,   0,   0],
        [  0, 646,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0, 802,   0,   0,   0,  43,   0,   0],
        [  0,   0,   0, 497,   0,   0,  23,   0,   0],
        [  0,   0,   0,   0, 523,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 571,   0,   0,   0],
        [  3,   0,  41,  15,   0,   0, 495,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0, 556,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 636]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.9766867160797119
      Test/F1Score          0.9764164686203003
        Test/Loss           0.07035357505083084
     Test/Precision         0

[{'Test/Loss': 0.07035357505083084,
  'Test/Accuracy': 0.9766867160797119,
  'Test/Precision': 0.9762660264968872,
  'Test/Recall': 0.9766867160797119,
  'Test/F1Score': 0.9764164686203003,
  'TestEpoch/Accuracy': 0.9765256643295288,
  'TestEpoch/Precision': 0.9765797853469849,
  'TestEpoch/Recall': 0.9765256643295288,
  'TestEpoch/F1Score': 0.9765474200248718}]

In [26]:
print(checkpoint_callback.best_model_path)   # prints path to the best model's checkpoint
print(checkpoint_callback.best_model_score) # and prints it score
best_model = MalwaresModelMLP.load_from_checkpoint("/home/<User>/repos/csg_is/training/sklearn_linear/lightning_logs/version_4/checkpoints/epoch=97-step=4116.ckpt", input_size = vectors.shape[1]-1, output_size = len(label_encoder.classes_))

trainer.test(best_model, dataloaders=val_dataloader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


/home/<User>/repos/csg_is/training/sklearn_linear/lightning_logs/version_5/checkpoints/epoch=28-step=1247.ckpt
tensor(0.9767, device='cuda:0')


Testing: |          | 0/? [00:00<?, ?it/s]

Epoch end: Test, epoch number: 0
TestEpoch/CM
 tensor([[518,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0, 646,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0, 811,   0,   0,   0,  34,   0,   0],
        [  0,   0,   0, 496,   0,   0,  24,   0,   0],
        [  0,   0,   0,   0, 523,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 571,   0,   0,   0],
        [  0,   0,   1,   8,   0,   0, 545,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0, 556,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 636]])
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Test/Accuracy         0.9888604879379272
      Test/F1Score          0.9878873825073242
        Test/Loss           0.04431302472949028
     Test/Precision         0

[{'Test/Loss': 0.04431302472949028,
  'Test/Accuracy': 0.9888604879379272,
  'Test/Precision': 0.9875195622444153,
  'Test/Recall': 0.9888604879379272,
  'Test/F1Score': 0.9878873825073242,
  'TestEpoch/Accuracy': 0.9885960221290588,
  'TestEpoch/Precision': 0.98741215467453,
  'TestEpoch/Recall': 0.9885960221290588,
  'TestEpoch/F1Score': 0.9877465963363647}]